### ISSUE TITLE
Assets for the Unity store

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#1]
Use the [Asset Store Tools](http://u3d.as/content/unity-technologies/asset-store-tools/1sF) to create the Unity asset package. Follow the [submission guidelines](http://unity3d.com/asset-store/sell-assets/submission-guidelines):

> Things should work as much as possible out of the box. If there are unavoidable setup steps to be performed by the user, such as defining Input Manager or Tag Manager settings, these should be clearly documented to support user experience and ensure overall satisfaction. Code packages should contain documentation that notify the user what he or she needs to set up [...]
> 
> We encourage you to support your quality content with great presentation material. You want to make a good impression and you want your asset to stand out from the crowd. The most successful publishers on the asset store have obtained their success by submitting complementary texts and preview images that justify the quality and usefulness of their assets. You can also entice your viewers by linking to website material, Unity webplayer demos and YouTube or Vimeo videos to create an interest among your audience. A short demonstration video usually makes a good first impression and shows what your asset is all about. This is especially helpful for demonstrating tools or editor extensions.
> 
> You must include documentation or at least a readme.txt file in your project. Please document what your asset does, setup or installation instructions, and how to use it. The documentation should be placed in the main folder of your package. It also helps to include a scene file that demonstrates your asset at work. If you are submitting updates frequently, we ask you to include a version history in your documentation and mention the changes in your notes to the submitter. 
> 
> Graceful handling of errors: Your asset must provide useful warnings to the user if he or she does something wrong. Under no circumstances should your extension throw null reference exceptions, unclear error messages or warnings. [...] Error messages must be in the form of a message / dialog or inline warning and explain how to fix the problem.
> 
> Pricing: Scripting Packages > Moderate > $50 - $95 (Increments of $5). 
> 
> For the sake of consistency, all Asset Store offerings are covered by a license we have created. Please have a look at the End User License Agreement to be sure you are comfortable with it. If you are offering your content for free, you have the further option of selecting one of three free-licenses, which override the basics of our commercial license.

...and lots more...

**Comment by ddutchie** [comment]
If you decide to make this an asset you should definitely make it easier to set up an initial scene. (For Some)
I'm thinking as an architect here, so imagine for archviz something along these lines.

eg: Hovercraft VR > Scenes, Lighting , Materials, Customization, About, Exit

Scenes > Load1, Load2, Load3 etc. - Loads Level/Scene
Lighting > Lighting1, Lighting 2, Lighting3. - Lights and Sun behaviour
Materials > Set1, Set2, Set3 - Different Materiality settings for a scene
Customization > Hovercraft customization
About > About Screen - Screen/Large panel with text
Exit> Exit to real life. 

In this way you could allow for the dev to drag assets/ groups of assets etc into slots in the scripts and it would just require some scene organisation. 

Regards
Gerard

**Comment by zachkinstner** [comment]
Good ideas. Moved to new issue: #6.

**Comment by ddutchie** [comment]
Not too sure how to contact directly, and unsure of where to post this. Have you seen this?

http://www.reddit.com/r/oculus/comments/2u1riy/virtual_desktop_unity_script/

In unity 4.6.x it places the game window on the rift at runtime so you dont have to build. 
Very useful tool for prototyping.

**Comment by zachkinstner** [comment]
Thanks for the heads-up, this does seem useful. 

Also, to contact me directly: zach at aesthetic interactive dot com.

**Comment by ddutchie** [comment]
Here is a example of customization of editor.

http://catlikecoding.com/unity/tutorials/editor/custom-list/

**Comment by zachkinstner** [comment]
For now, I'll provide `*.unityPackage` files via GitHub releases. 

I just posted **[the `v1.0.0` release](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases)**.
