### ISSUE TITLE
Jump-to-position slider feature

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#11]
@squakmix wrote:

> Traditional slider inputs allow users to click somewhere on the slider to change the value. You can see me trying to do it with Hovercast at [around 33 seconds in this video](https://www.youtube.com/watch?v=bUmUxLh2hn0&t=32s). It would be great if I could simply choose a value on the slider by hovering over that spot rather than hunting for the handle, activating it, and sliding it.

**Comment by zachkinstner** [comment]
I like this idea, but I'm not immediately sure how I'd want to approach the usability aspect. Thoughts:
- A) Give the handle selection priority. The "jump" would only work when you are trying to select a point far enough away from the handle.
- B) Make the entire slider one big selector. From any point, once you make a selection, the handle will jump immediately to the position nearest to the cursor.

A and B might be equivalent. The slider already "jumps" slightly if you select the handle while the cursor which is not immediately next to it. 

Another decision is about the slider handle, and whether it should be "active" (continuing to slide with the cursor) after the "jump" occurs.

**Comment by solderlocks** [comment]
I prefer option B with the described behavior; it would be nice to jump to a spot and be able to continue changing the value. That way I won't have to "re-grab" the handle after jumping if it doesn't quite land on the value I want.

**Comment by zachkinstner** [comment]
Yep, I think I'm in agreement with you. The next decision would be how to make it apparent to the user (via visual indicators, etc.) that this feature exists, and behaves in this manner. I'm open to ideas. I'm starting to slow down for the night, so I'll probably come back to this tomorrow.

**Comment by solderlocks** [comment]
I think a similar effect to a button being pressed (the overlay effect on the bar and fingertip loop contracting) would work great. Maybe instead of overlaying/highlighting the whole slider track when the user's input finger approaches, only highlight a wedge of space the size/shape of the slider handle on the track where the slider would be.

**Comment by zachkinstner** [comment]
I have started experimental work on this in the [`sliderjump`](https://github.com/aestheticinteractive/Hovercast-VR-Menu/tree/sliderjump) branch.

**Comment by zachkinstner** [comment]
I have merged the new "jump" feature into the `master` branch. The "jump" feature is enabled by default for sliders, but you can disable it via the `HovercastNavItem` "Allow Jump-To-Value" checkbox.

Feature animation:

![Loading slider jump animation...](http://www.aestheticinteractive.com/clients/hovercast/Hovercast-SliderJump.gif)

**Comment by solderlocks** [comment]
Cool - I love it! Can't wait to update my project with it.

**Comment by ddutchie** [comment]
yeah. that looks good.
