### ISSUE TITLE
Hovercast causes Unity Editor crash?

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#13]
From [Twitter conversation](https://twitter.com/z_zabaglione/status/568399160832966656)...

**@z_zabaglione:**

> そういえばHovercast-VR-MenuのテストをしていたらUnityEditorがクラッシュしまくっていた。どこが悪いのかわかりませんが、落ちるのは困り者です。。。。

Translated via Google:

> _Once you have the test of Hovercast-VR-Menu Speaking UnityEditor had earnestly crash. Where is I do not know how bad, but is troubled person fall. . . ._

**@zachkinstner:**

> @z_zabaglione what version of Unity are you using? Hovercast needs Unity 4.6 or higher (for Unity's new UI features).

**@z_zabaglione:**

> @zachkinstner I am using Unity4.6.2p2 on windows8.1

**Comment by zachkinstner** [comment]
**@zachkinstner:**

> @z_zabaglione hmm... do you have any crash logs or other info? I can investigate tomorrow. You could post here: (this ticket)

**Comment by zabaglione** [comment]
I think that problem of Unity or Oculus library(see movie).
http://youtu.be/Ul0OZn2RZxo

**Comment by zachkinstner** [comment]
Strange. As I understand from the video, you sometimes experience a Unity crash when trying to start/play the `LeapVR` scene within Unity. Other times, this works without a crash.

As you suggest, this could be a Unity or Oculus issue. I'm going to close this for now. But, if you find that there's something Hovercast-related in the crash log, please post it here and I can investigate further. Thanks for creating that video!

**Comment by zachkinstner** [comment]
@zabaglione, this discussion from the Leap Motion forum might be relevant to the Unity crash that you're experiencing: [Unity 4.6.2 Compatibility Issue](https://community.leapmotion.com/t/unity-4-6-2-compatibility-issue/2492)
