### ISSUE TITLE
Hoverboard VR Interface: Integration

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#18]
Here's the first video of **Hoverboard VR**:
https://www.youtube.com/watch?v=hFpdHjA9uR8

Currently, all the work on this is contained in the [`hoverboard` branch](https://github.com/aestheticinteractive/Hovercast-VR-Menu/tree/hoverboard/Unity/Assets/Hoverboard).

There are several common features between Hovercast and Hoverboard. Before merging it into the main branch, I think I will be doing some major refactoring to improve the organization and avoid duplicate code.

This may also involve extracting all core functionality into an engine-agnostic DLL. That would be a major step towards supporting [additional game engines](http://tirania.org/blog/archive/2014/Oct-23.html).

**Comment by grobm** [comment]
Cool, I was making a virtual keyboard as well.

-Mark Grob

**Comment by zachkinstner** [comment]
Hi @grobm! How is/was that work going? It would be good to see alternative approaches, since there are so many different UI/UX factors to consider.

**Comment by grobm** [comment]
Morning,

This is in regards to Hovercast and the your method of VR interface.

Great project, looking forward to the developments ahead.

-Mark Grob

**Comment by ddutchie** [comment]
This is beautiful, and it works.

But i think it should be a transition. 

For me a qwerty keyboard should be left out. Its a technology from the 19th century. It should die with vr. 

You should invest some time in predictive input. Or vocal commands. 

Have a look at minuum keyboard. Will send others when i remember their names. 

Regard
Gerard

**Comment by grobm** [comment]
I agree with the keyboard, may not be modern. Voice input would be the nice, or simply a google voice input widget. But, people do still use keyboards in some sense. Last time I check you typed this email on your iPhone? Or did Siri do it for you? Keyboards do provide an empirical input, is it affective, yes… efficient to other methods? maybe not.

The menu features is valuable, since this allows users to instance the instance of something or actions or other triggers in 3D space.

myTwo cents,

-Mark G.

**Comment by zachkinstner** [comment]
@ddutchie agreed, I see this as an intermediate step for text entry. It's important to note that Hoverboard is not simply for text input -- it can support any arrangement of buttons upon 3D planes. Those planes can be fixed to your camera, to world space, etc.

The text-keyboard demo is essentially VR [skeuomorphism](http://en.wikipedia.org/wiki/Skeuomorph). People are familiar with the text-keyboard layout and functionality, and thus will have an easier time learning/using it. I don't think it will be the most efficient/effective way to "type" in VR.

I have another concept in mind for a faster, non-traditional way to enter text. I don't know if it will work yet (needs a prototype). It would be a sphere (or hemisphere) of buttons attached to each index finger. You'd move your finger in the 3D direction of each button to select, then back to the center to reset.

**Comment by zachkinstner** [comment]
I think voice (speech-to-text) is an interesting approach for many cases. I could see it being a standard text-input method for VR. I don't know much about the technical aspects of STT.

I’d guess that STT doesn’t work well in scenarios like: non-word entry (usernames, codes, etc.), loud/talkative environments, noise-restricted environments (library), avoiding “critical” use cases (like someone else in the room turning your X-Box off), sensitive data (passwords, private notes), etc. Thus, other "quiet" forms of text entry would still be useful.

As I understand it, the voice features we use on mobile devices are all dependent upon a server (and internet connection) for parsing the audio information. That might also be seen as a negative for VR apps, especially if it involves extra server/service costs to the developer or user.

**Comment by grobm** [comment]
For local speech recognition, carnegie mellon and a few other sources have possible solutions.

**Comment by zachkinstner** [comment]
> I will be doing some major refactoring to improve the organization and avoid duplicate code.

This is happening in the [`ui-core` branch](https://github.com/aestheticinteractive/Hovercast-VR-Menu/commits/ui-core), and it probably deserves a separate issue...

**Comment by zachkinstner** [comment]
Please see https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/21 for discussion specific to the recent project refactoring. This refactor includes the improved Hoverboard support, so I'll close this ticket.
