### ISSUE TITLE
Support for Unity 5

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#19]
Via email:

> are you planning to upgrade Hovercast for unity 5? [...] it would be really nice having working input solution for vr coupled with improved graphics. 

I haven’t looked closely into Unity 5 yet, but my understanding is that there are several API/scripting changes. I’d have to decide if I want to convert the whole project to Unity 5 only, or if I should somehow support both.

**Comment by ddutchie** [comment]
I don't know if you have looked at this, but i'm running Hovercast in Unity 5 and I have not had issues. 

I have been since beta17. 

Honestly, i didnt even realise it was meant for unity 4.

**Comment by zachkinstner** [comment]
Ah, that's great to hear. I didn't realize you were using Unity 5. I'll send your note along to the person who emailed.

I'm going to leave this issue open for now, as well. I want to explore the new Unity 5 features a bit more, in case any of them are very useful for Hovercast/Hoverboard. If anyone has thoughts or insights about this, please let me know.

**Comment by ddutchie** [comment]
However, getting Leapmotion to work in Unity5 is another story

Delete the Leap.dll and LeapCShart.dll from Assets->Plugins->x86_64;
Get LeapCsharp.dll from https://leapmotion.app.box.com/s/w7j5q81x2604i2vn8d2hq9rvn171zydb3 
Replace LeapCsharp.dll in Assets root folder with one from website

That works and allows for testing within the editor.

**Comment by kirkokuev** [comment]
Hi, yes I can confirm that everything works fine in Unity 5 after modifications by ddutchie. BTW link for LeapCsharp.dll is dead. Use this instead:
https://leapmotion.app.box.com/s/w7j5q81x2604i2vn8d2hq9rvn171zydb

**Comment by kirkokuev** [comment]
Ok, not entirely fine. So, I am trying to attach HandController to HovercastSetup script as InputProvider via drag-and-drop and unity 5 just won't let me. In 4.6 drag-and-drop works perfectly.Looks like I have to do it in code.

**Comment by zachkinstner** [comment]
@kirkokuev In the current setup process, there's an easy step to miss. From [Getting Started](https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Getting-Started):

> **Input Provider:** In step 1, you found the Leap Motion "HandController" object. Attach the `HovercastLeapInputProvider` script to this object, and drag the object into the "Input Provider" input. 

Can you confirm that there is a `HovercastLeapInputProvider` script attached to your "HandController" GameObject?

In future versions, this will be easier. In my work in the `ui-core` branch, when you don't specify (via drag-and-drop in Unity) the providers, the code searches through the GameObjects to find a match.

**Comment by kirkokuev** [comment]
Ah, yes my bad, missed this step.

**Comment by zachkinstner** [comment]
The Hover VR project is still being built with Unity 4, but tests by myself and others all indicate that there aren't any known issues using Hover VR with Unity 5. Closing this issue.
