### ISSUE TITLE
The "Navigate Back" Button/Indicator

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#22]
Hovercast has been nominated for an award in experimental design! I have various small-ish improvements in mind prior to submitting the project to the competition, so I'm going to try to complete those today.

I'll post notes/screenshots as I go...

**Comment by ddutchie** [comment]
Congrats. 

Keep then improvements coming.

**Comment by zachkinstner** [comment]
The commit referenced above includes a new "navigate back" button that appears on the palm. Here's a quick animation showing the current functionality:

![Loading animation...](http://www.aestheticinteractive.com/hover/cast/Hovercast-Feature-PalmNavBack-640.gif)

The new button uses the same hover/selection process as the menu items. In addition, it also shows selection progress based upon the "Navigate Back Strength" value (for Leap input, this is related to the hand's grab strength). The button becomes available, and shows its arrow icon, whenever you are within a child menu level.

The design is currently very minimal. I'm open to ideas if anyone thinks more is needed here. I considered using a "grab" icon, but decided that it would be too specific to the Leap-based input.

One of my goals here was to make the "back" gesture more discoverable. Users are now able to visually see their progress toward completing the action. For example, a user might grab/close their hand slightly, and unexpectedly see the indicator -- they now know that the menu is "listening" to that kind of gesture. And, since this progress appears within the "back" button, the gesture becomes associated with the "back" action.

Thoughts/ideas?

**Comment by zachkinstner** [comment]
Tweet for this new feature: https://twitter.com/zachkinstner/status/594179574713417729

**Comment by zachkinstner** [comment]
Having an "always there" back button will also be useful for input types that don't have a good/reliable "back gesture" available.

It's not a perfect example, but it's particularly useful in the [`HovercastTest-TransformMenu-LookMouseCursor`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Unity/Assets/Hover/Demo/CastTest) test scene. This scene uses the mouse to approximate the "look" position, with the menu position set via a GameObject transform. With this setup (which I use for rapid testing), I can just use the mouse to navigate back.

**Comment by ddutchie** [comment]
I like it...

**Comment by grobm** [comment]
Great Zach!

My testers were commenting about the closing of the hand to go back.

-Mark

**Comment by zachkinstner** [comment]
@ddutchie, @grobm, thanks for the feedback!

I think I might give the button a subtle fade/transition when changing its "enabled" state (i.e. when moving between the root level and a child level).

**Comment by zachkinstner** [comment]
The [v1.1.0 release](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases/tag/v1.1.0) includes this new back button (and the fade animation noted above).
