### ISSUE TITLE
Hovercast VS Solution Build

### ISSUE THREAD

**Issue by TonyViT** [aestheticinteractive/Hover-VR-Interface-Kit#24]
There is an error while buliding your VS solution.
Post-build events of two projects (one is Hover.Board.Edit, the other is Hover.Cast.Edit) try to copy files to the directory \Assets\Plugins\Editor, but the Editor folder does not exist, so copy command fails.

Two possible solutions:
- Pre-create an Editor folder inside the Plugin folder (the workaround I used);
- Use the more powerful xcopy command or a more complex post-build script (I used xcopy in another project of mine)

**Comment by zachkinstner** [comment]
Hi @TonyViT -- I'm sorry for the delay. GitHub didn't send an email notification for this new issue.

Thanks for documenting this snag in the initial build process. For now, the first workaround (the one-time creation of the `/Assets/Plugins/Editor` directory) seems sufficient.
