### ISSUE TITLE
The attribute `System.Reflection.AssemblyDescriptionAttribute' cannot be applied multiple times

### ISSUE THREAD

**Issue by wj4y78308** [aestheticinteractive/Hover-VR-Interface-Kit#27]
Hello,
I got these errors "The attribute `System.Reflection.AssemblyDescriptionAttribute' cannot be applied multiple times" when I used this project in Unity5.

Other people who face the same problem said that just add the code below:
[System.AttributeUsage(AttributeTargets.All, Inherited = false, AllowMultiple = true)]
or just left one of the scripts.
I tried the first, getting nothing.
Therefore, I tried to delete all of them... and then I got a "Unity Bug Reporter".
Finally, I can't open my project.

I don't know what to do, but I really need this project . Can someone help me ,please.

**Comment by zachkinstner** [comment]
Hi @wj4y78308, sorry you're experiencing an issue! 

The Hover VR assemblies each use `AssemblyDescription` once per assembly. Here are the search results for this term: https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/search?utf8=%E2%9C%93&q=AssemblyDescription. 

Is there something in your error message that indicates this is related to Hover VR? Please check the error message's details and/or stack trace, as this may tell you exactly which assembly is causing the issue.

**Comment by wj4y78308** [comment]
Thanks for answering me. :)
However, I just use this project by opening the folder "Unity". Then, I moved some folder needed in the folder "Core".(such as folder "Solution")
Finally I got these error in all of the folder having "Properties/AssemblyInfo.cs" :
 "Assets/Solution/Hover.Board.Edit/Properties/AssemblyInfo.cs(5,12): error CS0579: The attribute `System.Reflection.AssemblyTitleAttribute' cannot be applied multiple times"

Is it that I lose some instruction needed or important scripts?

**Comment by zachkinstner** [comment]
>  moved some folder needed in the folder "Core".(such as folder "Solution")

Ah, this seems to be a common problem. The `Core` files are not meant to be included in the Unity project. Instead, the `Core` code gets compiled into DLL files. Those DLL files (whichever ones you want/need) are to be placed into your Unity project's `/Assets/Plugins` folder.

Please try the following:
- Remove all code related to Hover VR from your project.
- Download the [latest release](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases) (the `.unityPackage` file).
- Import that Unity package into your project. It contains everything you'll need for Hover VR itself (it does not include Oculus/Leap packages). The import will put the Hover VR files into their correct locations.

**Comment by wj4y78308** [comment]
Thanks : )
I'm the beginner in Unity ,so I don't know these things.
Now I have solved it!

**Comment by zachkinstner** [comment]
I'm glad it's working for you now!

It would be great to hear more about your project. If you'd like, you can [email me](mailto:hover@aestheticinteractive.com) about it.
