### ISSUE TITLE
Could not find HovercursorInput / Cursor is not appearing

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#28]
[Vince Vizzle](https://www.youtube.com/channel/UCNhBRPVdbhou0ShfKb9uGig) wrote via [YouTube comments](https://www.youtube.com/watch?v=Phn3Ix-YxPA):

> Does anybody know how to actually use these in unity? i followed the instructions and i keep getting "Could not find HovercursorInput" and "Could not find HovercastInput" errors

**Comment by zachkinstner** [comment]
@zachkinstner replied:

> Hi Vince! Is is possible that you missed the step "1i" from https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Hovercursor%20Integration? Hover VR supports multiple "input modules", so adding the relevant input component (such as `HovercursorLeapInput` or `HovercursorLookInput`) is an important part of the setup process.

I also provided a link to this new issue to continue the discussion

**Comment by VicerVersa** [comment]
so i deleted everything in the scene and started from scratch.  i just did everything on that page for leap input.  its not displaying the cursor though.  In step 2 it says to use an empty game object for the hovercursor.  should that gameobject have a mesh or a child object on it?  (ive tried both of these neither worked).

**Comment by zachkinstner** [comment]
I assume you're trying to add a cursor to the Leap Motion hands -- is that correct?

Based on step 2 (for Leap input) of the [Hovercursor Integration](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Hovercursor%20Integration), you will not need any child of that empty "Hovercursor" GameObject. However, please be sure that your "Hovercursor" GameObject A) is a child of your Leap Motion "HandController" GameObject, and B) has the `HovercursorSetup` script attached.

For additional info, you can look into the [Demo scenes](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Unity/Assets/Hover/Demo) to see various setup examples.

**Comment by VicerVersa** [comment]
yes i am trying to use the leap motion, and i did exactly that, it is still not working...

**Comment by VicerVersa** [comment]
I remember a few months back with the regular leap assets, there were some issues with dll files and the plugins folder etc.. between windows and mac version of unity.  Im currently running Windows 8.1 and unity 5.0.1fl and im assuming most of you guys use macs.  im not getting any erros like in the previously mentioned problem but could this have anything to do with why the cursor wont display?

**Comment by zachkinstner** [comment]
I'm using Windows 7 with both Unity 4 and 5. Let's see if we can figure out what's happening here. 
- Is it correct that you _do_ see your Leap Motion hands, but there is no white "cursor" circle appearing anywhere on them?
- Is there any output related to Hovercursor appearing in the console?
- Can you confirm that you have the `HovercursorLeapInput` attached to the Leap Motion "HandController" GameObject?
- Can you post (or [email](mailto:hover@aestheticinteractive.com)) screenshots of your object hierarchy in Unity, and also the editor panels for both `HovercursorSetup` and `HovercursorLeapInput`?

**Comment by VicerVersa** [comment]
Certainly
and by editor panels i assume you mean the inspector?
![image](https://cloud.githubusercontent.com/assets/9909850/7969338/cc27dd1a-09fb-11e5-87d6-f85e2cb9ec55.png)

![image](https://cloud.githubusercontent.com/assets/9909850/7969306/989a8240-09fb-11e5-9b53-ba40d5027b51.png)

(in play mode)
![image](https://cloud.githubusercontent.com/assets/9909850/7969314/a6b77f68-09fb-11e5-8311-0a3e897d1601.png)

![image](https://cloud.githubusercontent.com/assets/9909850/7969322/acec71cc-09fb-11e5-8e0b-381855869d2a.png)

![image](https://cloud.githubusercontent.com/assets/9909850/7969325/b3043d2e-09fb-11e5-81fb-e86fe2b2c3dc.png)

and yes I do see my hands on the screen

**Comment by zachkinstner** [comment]
Hmm... I was hopeful that these would give me the answer, but I'm still not sure what's happening here. A couple thoughts:
- Try removing the MeshRenderer on your "Hovercursor" object.
- Are you using the [v1.1 release](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases/tag/v1.1.0)? Note that the `master` branch has some significant changes that aren't fully tested or compatible with the v1.1 release.
- Can you confirm that the [`/Assets/Hover/Common/Resources/`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/v1.1.0/Unity/Assets/Hover/Common/Resources) folder (from v1.1, not `master` branch) is present in your project? It contains the shaders/materials that the cursor needs. Notably, the [shader](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/v1.1.0/Unity/Assets/Hover/Common/Resources/UnlitAlphaSelfIllumTop.shader#L11) uses `ZTest Always` to ensure the cursor is visible even if the hand model would otherwise obscure it.

I may need to get a (stripped-down) copy of your Unity project in order to reproduce and diagnose the issue.

**Comment by zachkinstner** [comment]
The setup process seems correct, and the console output is what I'd expect. That's why I'm looking in the "rendering" direction with my questions -- maybe the cursor is present but not visible. Here's another thought:
- At runtime, pause the Unity scene while your Leap Motion hand is visible. Are there GameObjects like "Cursor-LeftIndex" present as children of the "Hovercursor" GameObject? If so, please drill down into them to see what's happening within it. As a final child element in this hierarchy, there should be a "Ring" GameObject that contains a mesh.

**Comment by zachkinstner** [comment]
It sounds like @schurink is having the same issue:

> I attached all the scripts to the Handcontroller and Hovercursor gameobjects as described in the hovercursor wiki. However the cursor seems to be invisible. I am using the standard visual settings, standard settings from the HandControllerSandbox (renamed it to HandController), and I suppose I have set up the hovercursor setup script as described (default visual settings=hovercursor, input = handcontroller, camera transform = main camera). I tried to get it to work with both releases. Can you perhaps hint me on what I might be doing wrong?

**Comment by nwschurink** [comment]
I have created a new project and tried it again. Unfortunately still no luck. My hierarchy and inspector look like this:

![unity](https://cloud.githubusercontent.com/assets/12720130/7984162/397ac938-0ac7-11e5-9425-d97b0a8316f8.png)

![unity inspector](https://cloud.githubusercontent.com/assets/12720130/7984167/3f91f2f6-0ac7-11e5-92c3-5f78558fb832.png)

**Comment by zachkinstner** [comment]
I'm currently starting a new project from scratch to try to reproduce this issue. I'll let you know what I find.

**Comment by nwschurink** [comment]
As for the versions that I am using, I'm using Unity 5.0.2f1 personal and Leap Unity Core assets v2.30, I just saw that there is a v2.31 availale. Will try to use this instead to see if the problem persists and will let you know if it works.

**Comment by zachkinstner** [comment]
Steps to reproduce:
- Started new project (with Unity 5.0.2f1).
- Downloaded Leap Motion's [Unity Core Assets v2.3.1](https://developer.leapmotion.com/downloads/unity)
- Downloaded Hover VR [release v1.1.0](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases/tag/v1.1.0) (the `.unitypackage` file).
- Imported the entire Leap Motion "Unity Core Assets" package into the project.
- Imported the entire Hover VR package into the project. Clicked "Go Ahead" for the "Unity 5 API upgrade" dialog.
- Added "HandController" prefab to the scene.
- Created an empty "Cursor" object as a child of "HandController".
- Added `HovercursorSetup` component to "Cursor".
- Added `HovercursorLeapInput` component to "HandController".
- Start scene:
  - Two Hovercursor console outputs appear; no errors.
  - No cursor objects present in scene.

Prior to this test, I was using Unity 5.0.0f1 and an older version of the Leap SDK. I suspect there is a breaking change in the new Leap SDK. I will investigate.

**Comment by zachkinstner** [comment]
Here's the issue: Hovercursor discovers the various Hovercast/Hoverboard elements in the scene. These elements are responsible for telling Hovercursor which fingers are "active". Only "active" fingers receive a cursor. **Without a Hovercast/Hoverboard element in the scene, Hovercursor has no "active" fingers, so it displays no cursors.**

The following steps provide a minimal way to start seeing cursors. These are basically the first steps described in the Hovercast/Hoverboard integration documents.

For Hovercast:
- Add a "Cast" object as a child of "HandController".
- Add `HovercastSetup` component to "Board".
- Add a "Items" object as a child of "Cast".
- Add `HovercastItemHierarchy` component to "Items".
- Add `HovercastLeapInput` component to "HandController".
  - For table-mounted mode, set the "Active Palm Direction" to [0, -0.5, -1].
- The cursor will only be visible when the Hovercast menu is visible.

For Hoverboard:
- Add a "Board" object as a child of "HandController".
- Add `HoverboardSetup` component to "Board".
- Add a "Panel" object as a child of "Board".
- Add `HoverboardPanel` component to "Panel".

**Comment by zachkinstner** [comment]
The "CursorTest" demo scenes make the cursors appear by implementing a custom `IHovercursorDelegate` called [`DemoCursorToggle`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Unity/Assets/Hover/Demo/CursorTest/DemoCursorToggle.cs). This delegate tells Hovercursor which fingers to make "active", allowing the cursors to appear without any Hovercast/Hoverboard elements (which also provide their own `IHovercursorDelgate` implementations).

**Comment by zachkinstner** [comment]
To help avoid this confusion in the future (and to help me not forget about this next time!), I have added notes to the [Hovercursor Integration](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Hovercursor-Integration) docs:

> **Important note:** by default, Hovercursor will not display cursors on its own. Cursors will appear once there is a Hovercast or Hoverboard element in the scene.

...

> It is possible to display cursors _without_ a Hovercast or Hoverboard element in the scene. To do this,  create a custom [`IHovercursorDelegate`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Cursor/State/IHovercursorDelegate.cs) implementation, and [send that delegate to `HovercursorState`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Cursor/State/IHovercursorState.cs#L27).

**Comment by nwschurink** [comment]
Your sollution works perfect! Thanks for the help!

**Comment by VicerVersa** [comment]
Ive been really busy the past couple days but ill try to do that tonight.  Thank you for all your help. If it still doesnt work after adding the hovercast and hoverboard i will let you know.  Also, once everything is up and running perfectly i think itd be a cool idea to do one of those twitch specials on using these new assets since im sure other people.were having these issues too.
Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by VicerVersa** [comment]
Yhis worked and i am able to get the cursor to show.  th eproblem is that there is one cursor displayed in front of myu hand, how do you actually get the cursor to be attached to your fingers and palm like in the demo?

**Comment by zachkinstner** [comment]
@VicerVersa good question:

At the code level, each UI project (Hovercast or Hoverboard) specifies which cursor(s) it will use via the [`IHovercursorDelegate.ActiveCursorTypes`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Cursor/State/IHovercursorDelegate.cs#L11) property. For example, the [`HoverboardState`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Board/State/HoverboardState.cs) class implements the `IHovercursorDelegate` interface).

To configure this in Unity, you can attach a [`HovercastInteractionSettings`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Cast/Custom/HovercastInteractionSettings.cs) or [`HoverboardInteractionSettings`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Board/Custom/HoverboardInteractionSettings.cs) component. Both of these have a `Cursors` property (an array of cursor types) that you can set in the Unity inspector.
