### ISSUE TITLE
Importing results in errors

### ISSUE THREAD

**Issue by nwschurink** [aestheticinteractive/Hover-VR-Interface-Kit#29]
Hi,

I am trying to get the Hovercast VR interface project to work. What I did so far was opening the project folder in Unity. Then adding the Hovercast VR package. Opening monodevelop, and add the core files to the project. This however results in errors about double entries of UnityEngine.UI and LeapCSharp.NET3.5 assembly. However when I do not import the files in monodevelop I get errors about files missing like HoverBoardLayout. As I am rather new to Unity, I suppose that I am doing something wrong. Since now I have only tested and learned from projects that would instantly work after opening the project folder. Could you perhaps give a more detailed description about how to import the different packages and solutions from the core folder into monodevelop?

Thank you in advance,

Kind regards,

Niels Schurink

**Comment by nwschurink** [comment]
Note: I am using the latest hovercast version and the free edition of the last version of unity.

**Comment by ddutchie** [comment]
Open a new project and import the release version. Its a unitypackage somewhere on github. 

It should work.

**Comment by nwschurink** [comment]
The problem is that I just don't know where to put the files. What I did was "open project" in Unity and select the "\Hover-VR-Interface-Kit\Unity" project folder. Then import package "HoverVR-1.1.0.unity". Select sync monodevelop. And then I'm actually stuck. I tried adding the core files by right clicking the Unity solution folder -> add project -> and then add the individual .csproj files from the "\Hover-VR-Interface-KIT\Core\Sollutions*" to the unity solution folder. However then I get error messages about that UnityEngine.world is not defined. I suppose that I have to add the "Hover-VR-Interface-Kit\Core\Packages\" also, but don't know where to put these. Should I include them in the assets folder, or add them as files in monodevelop? If you would be so kind as to explain in a step by step manner how to import the Hover-VR-Interface, you would really make my day. I am getting pretty frustrated as I'm not able to get it to work :)

**Comment by zachkinstner** [comment]
Hi @schurink, I think the discussion in #27 is similar to this one -- please see my latest comment there. 

You won't need to download/use anything directly from the Hover VR code repository. Instead, you can download/import the `.unitypackage` file from the Hover VR [releases](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases) page. (Note: the Hover VR release package does not include the Oculus/Leap packages.)

I'll try to make all of this more clear in the documentation when I post the next Hover VR release (v1.2).

**Comment by nwschurink** [comment]
@zachkinstner Thank you for your response, didn't thought it was that easy :) One problem remains however. I attached all the scripts to the Handcontroller and Hovercursor gameobjects as described in the hovercursor wiki. However the cursor seems to be invisible. I am using the standard visual settings, standard settings from the HandControllerSandbox (renamed it to HandController), and I suppose I have set up the hovercursor setup script as described (default visual settings=hovercursor, input = handcontroller, camera transform = main camera). I tried to get it to work with both releases. Can you perhaps hint me on what I might be doing wrong?

**Comment by zachkinstner** [comment]
@schurink I have moved your latest question to issue #28, where someone else is experiencing the same issue. Let's see if we can figure out what's going on...

**Comment by zachkinstner** [comment]
> I'll try to make all of this more clear in the documentation

Please see the new [Getting Started](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Getting-Started) wiki page.
