### ISSUE TITLE
Hover VR Release: v1.2.0

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#30]
Please see the [v1.2.0 release page](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases/tag/v1.2.0). We can use this ticket to discuss the latest changes and any related issues/questions that might come up.

This release provides many upgrades to Hoverboard. It now includes support for sliders, radio sets, checkboxes, and sticky items -- much like Hovercast. The Hoverboard sliders can be oriented horizontally or vertically (the slider uses the longer dimension to determine the orientation). Here is an example of slider usage:

![Loading slider animation...](http://www.aestheticinteractive.com/hover/board/Hoverboard-Slider-640.gif)

The sliders in this animation show a new feature: an customizable "start location" for the fill. You can choose the minimum value, maximum value, or the zero value as the starting point. This feature is available for both Hoverboard and Hovercast.

The other major update in v1.2.0 is related to rendering performance. By sharing materials/textures/shaders (and using vertex coloring) across the various items and item layers, this release drastically reduces the number of required draw calls. This may have an impact on existing integrations, possibly causing issues related to transparency and/or depth-ordering.

**Comment by zachkinstner** [comment]
Please check out my recent demo video of "Firework Factory VR":
**https://www.youtube.com/watch?v=pJXiKb_R_2s**

---

![Loading Firework Factory VR animation...](http://www.aestheticinteractive.com/clients/fireworks/StarMenu.gif)

The UI is built upon the latest v1.2.0 Hoverboard features. I have created customized item renderers, which allow me to place 3D icons/models on individual items, have a dynamic "tab" shape, etc.

**Comment by ddutchie** [comment]
Hello zach, I integrated the latest packaged release into a project no problem, but I am having some issues setting up a hoverboard. 

I have followed all steps, but I cant seem to figure out how to design a layout. All my panels seem to ly on top of each other. 
Perhaps include a set of hover prefabs in the next release.

Opening the full project from github crashes unity. 
Fireworks Factory is awesome.

**Comment by ddutchie** [comment]
Getting somewhere. Are you working on curved panels at all?

**Comment by ddutchie** [comment]
one more thing. How could I combine both look and leap input onto a Hoverboard panel. 
It throws some exception when trying to combine both by having multiple hovercursors in the scene.

**Comment by ddutchie** [comment]
Also, I am looking for a way to add background to a panel? is this relatively simple?

**Comment by zachkinstner** [comment]
Hi @ddutchie,

> I cant seem to figure out how to design a layout. All my panels seem to ly on top of each other.

The docs probably don't go into enough detail on this -- I can try to improve them a bit. It's worth looking through the example scenes (like the ["BoardTest" scenes](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Unity/Assets/Hover/Demo/BoardTest)) to see how the layouts are configured.  If your `HoverboardLayout` elements are all on top of each other, I think you'll need to set the "Position" property of each one. The "Position" represents the 2D (x/y) position of the layout upon the parent `HoverboardPanel` plane.

> Opening the full project from github crashes unity.

You mentioned later that you were "getting somewhere" -- did you figure out this issue? If you have debug output or error text, please post those details. This kind of issue might occur if the files from the previous Hover VR version were not removed before installing the latest version.

> Are you working on curved panels at all?

I started on a concept like this several months ago (before Hover VR). I might revive it at some point, and/or find a way to include it as a stanadard Hover VR element.

> I am looking for a way to add background to a panel? is this relatively simple?

You could accomplish this (and possibly curved panels) by creating custom item renderers. I did this extensively with the Firework Factory VR project. I'd consider this an "advanced" task with Hover VR, and unfortunately I don't have docs or open-source examples at this point. 

If you want to try it out, you can review the code for [the "Standard" Hoverboard renderers](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Core/Solution/Hover.Board/Display/Standard). I tried to write these renderer classes in a way that allows for subclasses to extend/modify the original behavior.
