### ISSUE TITLE
Hover VR Release v1.4.0

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#34]
Please see the [v1.4.0 release page](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases/tag/v1.4.0). We can use this ticket to discuss the latest changes and any related issues/questions that might come up.

If you are trying to use Hover VR for the first time, please read the [Getting Started](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Getting-Started) page (and the other documentation) to help you get everything set up correctly.

---

This release is focused on updating Hover VR for use with the latest Unity, Leap Motion, and Oculus assets -- see https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/issues/32 for details. 

The changes in this release make Hover VR v1.4.0+ incompatible with the older versions of Unity and older versions of the Leap Motion and Oculus assets.

**Comment by yesh66** [comment]
Dear Zachkinstner, Can we customize the functionality of the menu items to change the scenes or control animations? I have been trying to create Custom Hovercast Item Listeners for this, but they do not seem to work. Wanted to find out if it is possible at all and if you can guide me anyway?
Thanks and best wishes.

**Comment by zachkinstner** [comment]
Hi @yesh66, regarding the listeners not working -- are you able to receive/handle the events? For example, if you place a `Debug.Log()` output in your listener, do you see the output on a selection event?

By the way, I'm slowly making progress on version 2.0 of Hover VR, which will make listeners (and many other things) easier for developers to use and customize. I don't have a target release date for this, however, as my consulting work is taking the majority of my time right now.

**Comment by zachkinstner** [comment]
The [**v2.0.0A (alpha)** release](https://github.com/aestheticinteractive/Hover-UI-Kit/releases/tag/v2.0.0A) is now available. This release is substantially different from the **v1.x** releases. Please see the [project wiki](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki) for details.
