### ISSUE TITLE
Is it possible to use an image for a hovercast item?

### ISSUE THREAD

**Issue by ahsquared** [aestheticinteractive/Hover-VR-Interface-Kit#36]
I would like to use an image for my hover cast items, instead of just text and colors. Is that possible?

**Comment by zachkinstner** [comment]
It's possible, but it will require writing a custom renderer. Eventually, it would be a good feature to add support this kind of thing (and other settings/options) within the "standard" renderers.

For Hovercast, the code for the standard renderers is [here](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Core/Solution/Hover.Cast/Display/Standard) and the code for the renderer's visual settings is [here](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Core/Solution/Hover.Cast/Custom/Standard). Custom renderers are an advanced topic, and I haven't had a chance to write documentation for this process. If you do give it a try, we can use this topic for Q&A.

**Comment by ahsquared** [comment]
Finally got some time to look into this:

I'm not sure if this is the right way to do this, but it felt like the simplest way to add an image background to the hover cast renderers. I applied it to UISelectItemRenderer. I wasn't sure about adding it globally or adding it to each renderer so just started with this one.
There is an updateBackgroundImage method where I change the main Texture and shader, and had to change the translation slightly as I was getting weird artifacts from the text and highlights. I'm sure there is a better way to do this...

``` csharp
    public virtual void UpdateBackgroundImage(Texture pTexture) {
            if (pTexture != BackgroundImage && pTexture != null)
            {
                Background.GetComponent<MeshRenderer>().material.mainTexture = pTexture;
                Background.GetComponent<MeshRenderer>().material.shader = Shader.Find("SelfIllumAlpha"); // better way??
                Background.transform.Translate(0, 0.001F, 0); // better way??
            }

            BackgroundImage = pTexture;
        }
```

These are the files with changes:
Core/Solution/Hover.Cast/Custom/Standard/HovercastItemVisualSettingsStandard.cs
Core/Solution/Hover.Cast/Custom/Standard/ItemVisualSettingsStandard.cs
Core/Solution/Hover.Cast/Display/Standard/UiItemSelectRenderer.cs
Core/Solution/Hover.Common/Display/UiHoverMesh.cs

You can see my changes here: https://github.com/ahsquared/Hover-VR-Interface-Kit/commit/65e10f2e8d346e3c11e97ac96c4065fd6ac46c15

Thoughts?

**Comment by zachkinstner** [comment]
Hi @ahsquared, sorry for the long delay. My consulting work has been keeping me very busy, and I've fallen behind on my own projects.

I have not had a chance to review this work, but thank you very much for posting it. Over a few days in January, I have started the process of revising the way items are structured and configured in Unity. If you're curious, this is happening in the [`items` branch](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/commits/items). As part of this work (which I expect will be v2.0, and not backwards compatible) I plan to improve the way developers can modify the look of the items, including support for materials.

**Comment by zachkinstner** [comment]
@ahsquared, the [v2.0.0A (alpha) release](https://github.com/aestheticinteractive/Hover-UI-Kit/releases) is now available. In v2.0, it is much easier to customize items, and you can do so without any custom code. Each item's entire "renderer" structure is present (and visible) in the editor, and most properties are adjustable. For now, there is just one default [renderer](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Renderers) type for items (from the "Alpha" [renderer module](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Renderer-Modules)), but anyone can create more (possibly without much/any custom code).

I made a new [**Customize Items**](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Getting-Started%EA%9E%89-Customize-Items) wiki page today. I hope to add more examples there soon, but for now it contains instructions (and corresponding animation) for changing the materials within an item renderer:

![Customize Item Material](../wiki/Images/GettingStarted-Customize-ItemMaterial.gif)

**Comment by zachkinstner** [comment]
I'm going to close this ticket for now, but we can re-open it if needed.
