### ISSUE TITLE
mouse / screen point for hovercursor

### ISSUE THREAD

**Issue by yuchizhong** [aestheticinteractive/Hover-VR-Interface-Kit#37]
Hi,
I really like this project and enjoyed experimenting different features.
However, in one of the future projects I'm building, I need to use mouse for precise object picking and movement, because the leap motion is lack of stability and accuracy, especially for HMD. So I wonder that if I can use mouse as a cursor while using right hand fingers for cursors too, so that people don't need to switch between right hand and mouse frequently. That may also help later for other types tracking devices such as a single-hand controller.

The current approach I come up is recasting from the screen point to the renderer, but this is complicated and resources consuming. So I wonder if I can try subclassing or write a class similar to look input? I am seeking for help or hint about this because I cannot figure that out by reading the source code (I'm bad at coding).

Thanks in advance, and I'll share my work after I get this done.

**Comment by zachkinstner** [comment]
Hi @yuchizhong, I won't be able to help for the next several days. However, please have a look at the "LookMouseCursor" scene [here](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Unity/Assets/Hover/Demo/BoardTest) and the "TransformMenu-LookMouseCursor" scene [here](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Unity/Assets/Hover/Demo/CastTest). These might be very helpful for you.

In my [Firework Factory VR](https://share.oculus.com/app/firework-factory-vr) project, I provide a non-VR version which uses the mouse cursor to control the Hoverboard panels. So, this can be done, but the cursor position/behavior might not be exactly what you'd expect.

**Comment by yuchizhong** [comment]
Thanks, I got this thing work by combining the leap and look input scripts to one. (below)
I also tried to combine the hovercast normal and transform (so a right-click can call out the menu without hand, but you can also use hand as a priority, but the internal Build function prevented me and I dont want to change the base code).

So I finally reach the following code. (dont blame me for the style or logic, im bad at coding)
With this script adding Look to cursors list and then you can use mouse.
Basically you need to add a camera as a child of main camera, and set that camera to be the HeadsetCameraTransform here, and it looks to where your mouse cursor points, and the hovercursor always in that camera's center.
The look cursor IsAvailable is readonly, so if want to disable that temporarily (see IfUseLookInput),  I need to make the camera look up so it doesnt points on anything. So if you also want to use normal look and fingers as same time, you can just set IfUseLookInput=false and (set the camera rotation to vector3.zero or use the main camera as HeadsetCameraTransform)
One more thing is that in the Update function, you need to provide the position of your mouse cursor by your own, because in VR we use virtual cursor (you cannot see your mouse in VR).

using System;
using System.Collections.Generic;
using Hover.Common.Input;
using Hover.Common.Input.Leap;
using Hover.Cursor.Input.Leap;
using Hover.Common.Util;
using Leap;
using Hover.Cursor.State;
using UnityEngine;
using System.Collections.ObjectModel;

namespace Hover.Cursor.Input.Multi
{
    /_================================================================================================_/
    public class HovercursorMultiInput : HovercursorInput
    {
        private GameObject root = null;

```
    private Controller vLeapControl;
    private List<IInputCursor> vCursors;
    private Dictionary<CursorType, IInputCursor> vCursorMap;
    private Dictionary<CursorType, bool> vSideMap;

    //look
    private static readonly Action<PlaneState, PlaneData> InitStateFunc = ((s, d) => s.Init(d));

    public Transform HeadsetCameraTransform;
    public float CursorSize = 0.1f;
    private bool UseMouseForTesting = false; //always false
    public float MousePositionMultiplier = 0.4f;
    public bool IfUseLookInput = false; //if you want to turn on mouse, set this to true

    private Hover.Cursor.Input.Look.InputCursor vCursor;
    private CacheList<PlaneState> vPlaneStates;


    ////////////////////////////////////////////////////////////////////////////////////////////////
    /*--------------------------------------------------------------------------------------------*/
    public virtual void Awake()
    {
        vLeapControl = new Controller(); //GC_ALLOC: every frame
        vCursors = new List<IInputCursor>();
        vCursorMap = new Dictionary<CursorType, IInputCursor>(EnumIntKeyComparer.CursorType);
        vSideMap = new Dictionary<CursorType, bool>(EnumIntKeyComparer.CursorType);

        //look
        Hover.Cursor.Input.Look.InputSettings sett = new Look.InputSettings();
        sett.InputTransform = gameObject.transform;
        sett.CameraTransform = HeadsetCameraTransform;
        sett.CursorSize = CursorSize;
        sett.UseMouseForTesting = UseMouseForTesting;
        sett.MousePositionMultiplier = MousePositionMultiplier;

        if (HeadsetCameraTransform == null)
        {
            IsFailure = true;
            throw new Exception("Requires the 'Headset Camera Transform' to be set.");
        }

        vCursor = new Hover.Cursor.Input.Look.InputCursor(CursorType.Look, sett);
        vPlaneStates = new CacheList<PlaneState>();
    }

    void Update ()
    {
        //determine if to use look input
        if (IfUseLookInput)
        {
            HeadsetCameraTransform.LookAt(---some vr cursor's world postion---);
        } else
        {
            HeadsetCameraTransform.localRotation = Quaternion.Euler(new Vector3(90, 0, 0)); //just look up
        }
    }

    ////////////////////////////////////////////////////////////////////////////////////////////////
    /*--------------------------------------------------------------------------------------------*/
    public override void UpdateInput()
    {
        Frame frame = LeapUtil.GetValidLeapFrame(vLeapControl);
        Hand leapHandL = LeapUtil.GetValidLeapHand(frame, true);
        Hand leapHandR = LeapUtil.GetValidLeapHand(frame, false);

        if (!IsEnabled)
        {
            leapHandL = null;
            leapHandR = null;
        }

        foreach (IInputCursor cursor in vCursors)
        {
            if (cursor.Type == CursorType.Look)
            {
                if (cursor != vCursor)
                {
                    Debug.Log("look cursor problem");
                }

                ReadOnlyCollection<PlaneData> planeDataList = vPlaneProviderFunc(vCursor.Type);

                vPlaneStates.RebuildWith(planeDataList, InitStateFunc);
                vCursor.UpdateWithPlanes(vPlaneStates.ReadOnly);
            } else
                ((InputCursor)cursor).UpdateWithHand(vSideMap[cursor.Type] ? leapHandL : leapHandR);
        }
    }

    /*--------------------------------------------------------------------------------------------*/
    public override IInputCursor GetCursor(CursorType pType)
    {
        if (pType == CursorType.Look)
        {
            if (!vCursorMap.ContainsKey(pType))
            {
                vCursors.Add(vCursor);
                vCursorMap.Add(pType, vCursor);
            }
            /*
            throw new Exception("The " + typeof(HovercursorLeapInput) + " component does not support " +
                "the use of " + typeof(CursorType) + "." + pType + ".");
                */
        }

        if (!vCursorMap.ContainsKey(pType))
        {
            var cursor = new InputCursor(pType);

            vCursors.Add(cursor);
            vCursorMap.Add(pType, cursor);
            vSideMap.Add(pType, CursorTypeUtil.IsLeft(pType));
        }
        return vCursorMap[pType];
    }
}
```

}
