### ISSUE TITLE
Change on runtime a Panel Item Label text

### ISSUE THREAD

**Issue by edmundo096** [aestheticinteractive/Hover-VR-Interface-Kit#38]
I have an Item of type Selector, working good.
But I have not found any way of updating the resulting label manually by code.

It's possible to do that? If so, how?
Regards.

**Comment by zachkinstner** [comment]
Hi @edmundo096, please try `GetItem()`:

``` c#
HovercastItem hoverItem = [...] //most likely, you'd get this component from a GameObject
ISelectorItem item = (ISelectorItem)hoverItem.GetItem();
item.Label = "New Label";
```

The current system uses the "Hover-" prefixed classes as the Unity scripts/components, and these generate the core items (which implement the `IBaseItem` interface). Its those core items that get used within the Hover VR internals -- the "Hover-" classes are responsible only for initializing those items based on the setup within the Unity editor.

If you want to look into the code, please see [`HovercastItem`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Cast/Items/HovercastItem.cs) and [`IBaseItem`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Common/Items/IBaseItem.cs).

This separation of "item components" vs. the "core items" has caused confusion for other developers, as well. When I have more time to work on Hover VR again, I will try to improve this.

**Comment by edmundo096** [comment]
I will try to check this the following weeks/weekends, and comment any results.
Thanks!
