### ISSUE TITLE
Is it possible to change the grid style to hex?

### ISSUE THREAD

**Issue by grobm** [aestheticinteractive/Hover-VR-Interface-Kit#39]
Hey Hover Crew,

I am bring this back to a project that is UI themed based on Hex and not a square grid. How would you change the style of layout for circular or hex based layouts? Right now the children position based on square layout. Suggestions?

**Comment by zachkinstner** [comment]
Hi @grobm, sorry for the very long delay. My consulting work has been keeping me very busy, and I've fallen behind on my own projects.

To make a hexagon or circle shaped Hoverboard item, you'd need to build a custom renderer. This is an advanced topic that I haven't documented yet. An example is the default [`UiItemSelectRenderer`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/blob/master/Core/Solution/Hover.Board/Display/Standard/UiItemSelectRenderer.cs), which also serves as a base class for some of the other item types. The renderer is responsible for building its own geometry and labels (or loading them from a prefab at runtime) and connecting those elements to the incoming data (like the size, item text, and proximity/selection percentages).

Once you have hex-shaped items, I think the positioning/layout could consist of regular rows, where every other row is offset horizontally by 0.5x of an item width.

In future versions, I plan to make it easier for developers to build renderers, and try to simplify the architecture/settings that supports them. 

I have also built (as a part of "Firework Factory VR") some initial tools for more complex layouts -- I'd like to bring some of that code into the Hover VR core. Or, potentially make use of existing layout tools like Unity's Canvas, which would already be familiar to developers.

**Comment by grobm** [comment]
Thanks Zack, I hacked something like hovercast in Leapmotion's Orion samples, but I will look at this code again.

**Comment by grobm** [comment]
Saw you on the Meta2 Reel. :-) Nice! I think I need to update my Meta to the Meta2.

**Comment by zachkinstner** [comment]
Hah, you found me! ([Meta launch video](https://www.youtube.com/watch?v=_x9462x6A0k))

I think you'll be pleased with the upgrade from Meta1 to Meta2 :)
