### ISSUE TITLE
One-handed usage mode

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#4]
I think the menu can be fully functional with just one hand. The initial idea is: 
- Cycle through highlighted items by rotating the hand about the palm axis.
- Select/release items by moving in/out along the finger direction.
- Provide new visual indicators to help learn/perform these movements.

**Comment by zachkinstner** [comment]
The look-based selections in https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/7 are working well for one-handed mode, too.

**Comment by zachkinstner** [comment]
Watch the new **["Leap Look" demo video >](https://www.youtube.com/watch?v=1xcVdYGffdY)**.

**Comment by solderlocks** [comment]
This works beautifully and was really easy to integrate into my project. Thanks for the awesome updates/new features lately Zach!

**Comment by zachkinstner** [comment]
You're welcome -- thanks for the feedback! It's always good to know what's working (and what's not) for devs and users.

**Comment by zachkinstner** [comment]
I'm closing this issue for now. I think the one-handed "Leap Look" mode is better than the idea that I described at the beginning of this ticket.
