### ISSUE TITLE
How to trigger any function

### ISSUE THREAD

**Issue by Subrat08** [aestheticinteractive/Hover-VR-Interface-Kit#40]
In simple menus where A,B,C has been written as child of Menu,I want if a player press A then he should redirect to any other scene. Please help me How to do this

**Comment by zachkinstner** [comment]
Hi @subrat94, sorry for the long delay. My consulting work has been keeping me very busy, and I've fallen behind on my own projects.

Please see the documentation on [Item Listeners](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Hovercast%20Item%20Listeners). In future versions, I plan to support `UnityEvent` properties on the menu items, which should simplify this process.
