### ISSUE TITLE
Multiple menus? 

### ISSUE THREAD

**Issue by JobsBan** [aestheticinteractive/Hover-VR-Interface-Kit#43]
Hi, 
Thanks for your amazing job.

Is there a way to get more than one menu on the scene? 
I would like to be able to get some menus, or a way to navigate in the menu thanks to the scripts (sorry for my bad english). 

Thanks.

**Comment by zachkinstner** [comment]
Hi @JobsBan, do you mean "Hovercast" or "Hoverboard" menus?

For Hovercast, which attaches to your hand, you could potentially switch between entirely different menus, but they wouldn't be visible at the same time.

For Hoverboard, there can be any number of menus placed in the scene. To handle scenarios like nested menus, you'll likely need to do some custom scripting work. You can see an example of a more complex menu system built with Hoverboard in my [Firework Factory VR](https://www.youtube.com/watch?v=Tm9E24aZPJc) video.

By the way, I'm slowly making progress on version 2.0 of Hover VR, which will make the menus easier for developers to use and customize. I don't have a target release date for this, however, as my consulting work is taking the majority of my time right now.

**Comment by zachkinstner** [comment]
Hi @JobsBan, you should be able to place many items into a scene. This is easier to do in v2.0, and note that you can use [layouts](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Layouts) to keep groups of items arranged nicely. Please see the v2.0 [Getting Started](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Getting-Started) wiki pages for details about creating and placing items in your scene.

If you're referring to multiple Hovercast menus, this too is possible. The latest version of Hovercast allows you to swap in a new "active row" (via editor or script) whenever you need, where each "row" contains its own set of items. Alternatively, you could make multiple Hovercast instances in your scene, then enable a particular one (and disable all others) whenever you need. See the [Hovercast interface module](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Interface-Modules%EA%9E%89-Cast) wiki page for details.
