### ISSUE TITLE
Support for GNU/Linux OS

### ISSUE THREAD

**Issue by DmitryHetman** [aestheticinteractive/Hover-VR-Interface-Kit#45]
Add support for GNU/Linux.

**Comment by zachkinstner** [comment]
Hi @DmitryHetman, this project is currently built for use with the Unity 3D engine, so it will be compatible with any OS that Unity supports (I thought Linux was one of them).

This project can also support (via [input modules](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules)) many different input devices and VR/AR headsets, but I don't have any control over the OS compatibility of these devices.
