### ISSUE TITLE
Enable/Disable Hovercast Menu

### ISSUE THREAD

**Issue by JobsBan** [aestheticinteractive/Hover-VR-Interface-Kit#46]
Hi!
First, thanks for your amazing job. 

Is there a way to enable and disable the visibility and the activation of the menu? 
I want to do it via script, but I don't know if that's possible. 

(Sorry for my really bad English).
Thank you.

**Comment by zachkinstner** [comment]
@JobsBan, the [v2.0.0A (alpha) release](https://github.com/aestheticinteractive/Hover-UI-Kit/releases) is now available, and this new version provides multiple ways to achieve your goal.

In v2.0, Hovercast is an [interface module](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Interface-Modules%EA%9E%89-Cast), and includes an "open/close" button that expands or collapses the menu. You can also disable Hovercast's entire GameObject if you want the interface to be completely invisible/ignored. Here's an animation showing the "open/close" button:

![Hovercast](../wiki/Images/InterfaceModule-Hovercast-LeapMotion.gif)
