### ISSUE TITLE
Hover UI Kit Release: v2.0.0A (alpha)

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#47]
Please see the [**v2.0.0A (alpha) release page**](https://github.com/aestheticinteractive/Hover-UI-Kit/releases/tag/v2.0.0A). This ticket is for discussion about the latest changes, including any bugs, issues, and questions that might come up.

This release is substantially different from the **v1.x** releases. Please see the [**project wiki**](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki) for an overview of the project, instructions for getting started, and details about project features.

**_This is an "alpha" release. It has not yet been tested in production-level applications, and there may be many breaking changes prior to the official v2.0 release._**

**Comment by grobm** [comment]
Nice!! Going to be updating VR Admin tool with this. Great Work Zach!

**Comment by zachkinstner** [comment]
Thanks @grobm! 

I should note that **v2.0 is not compatible with previous versions**. I know this is unfortunate for many of you who have already implemented some interfaces with v1.x, but I couldn't achieve my goals for v2.0 (especially given my limited work time) and also maintain compatibility. 

Hopefully, everyone will find the v2.0 system to be easier to work with and to customize, which may make the transition a bit less painful. The wiki has several [Getting Started](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Getting-Started) instructional pages that should help. I'd love to hear feedback (this is an "alpha" release after all) on everything -- functionality, features, ease-of-use, documentation, and so on.

We can also use this ticket to consolidate tips/approaches for migrating from v1.x to v2.x.

**Comment by zachkinstner** [comment]
Here's the [alpha release email](http://us14.campaign-archive1.com/?u=561a66a68d88099d25b2caa3e&id=8c1eef3178). If you'd like to receive these email updates, please [subscribe](http://aestheticinteractive.us14.list-manage.com/subscribe?u=561a66a68d88099d25b2caa3e&id=a6541db81c) to the list.

**Comment by ilanb** [comment]
Hi,
Any chance to provide example with button icon like in your Fireworks project ? In some case is usefull to have just Icon, no text etc... maybe you can add to item type ? 
Great update anyway :-)

**Comment by zachkinstner** [comment]
Thanks @ilanb -- good idea. I created a new issue (#48) for this.
