### ISSUE TITLE
Implement support for Oculus Touch

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#52]
Hover UI needs an input module for Oculus Touch. Here are some links to get started:

- [Oculus Utilities for Unity 5](https://developer3.oculus.com/downloads/game-engines/1.10.0/Oculus_Utilities_for_Unity_5)
- [Avatar SDK](https://developer3.oculus.com/downloads/pc/1.10.1/Oculus_Avatar_SDK) for controller/hand models
- [`OVRInput` Documentation](https://developer3.oculus.com/documentation/game-engines/latest/concepts/unity-ovrinput)

**Comment by zachkinstner** [comment]
By default, the index and thumb cursors follow transforms within the "OVRAvatar" hand model:

![oculustouchinput001](https://cloud.githubusercontent.com/assets/3940764/21199123/1cb23adc-c210-11e6-8911-088645bc8688.gif)

This can be disabled via the `HoverInputOculusTouch` component's "Use Hand Transforms" checkbox.

Regardless of the hand transforms, the other cursor types (palm, middle, etc.) follow a pattern (relative to the center of the Touch controller) similar to the pattern used by the [Vive input module](../wiki/Input-Modules%EA%9E%89-Vive).

**Comment by zachkinstner** [comment]
The input module now provides more per-cursor settings:

![image](https://cloud.githubusercontent.com/assets/3940764/21271785/58f32d64-c38a-11e6-8499-e40e4aa153d9.png)

|Property|Description|
|:---|:---|
|*Local Position/Rotation*|Applied to the cursor as local offsets from the controller center.|
|*Should Follow Avatar Element*|Uses an `OvrAvatar` transform to set cursor position/rotation (ignoring the local offsets). By default, this is used for "index" and "thumb" cursors, since the `OvrAvatar` hand models move those two fingers based on the current pose.|
|*Avatar Element Name*|The name of the desired `OvrAvatar` transform to follow. Oculus Touch generates these transforms at runtime, so they must be found via name.|
|*Trigger Strength Input*|The axis/button that controls the cursor's "Trigger Strength".|
|*Cursor Size Input*|The axis/button that controls the cursor's "Size".|
|*Min/Max Size*|The cursor's size boundaries. By default, the cursor is sized via the midpoint between  these two values.|

The two "Input" properties allow the following selections:

|Option|Description|
|:---|:---|
|*None*|Ignores input, defaults to 0% (trigger strength) or 50% (cursor size). |
|*Index Trigger*|Uses the index-finger trigger's linear value.|
|*Hand Trigger*|Uses the hand/squeeze trigger's linear value.|
|*Button 1 Press*|Uses the first ("A" or "X") button's boolean value.|
|*Button 2 Press*|Uses the second ("B" or "Y") button's boolean value.|
|*Start Press*|Uses the third button's boolean value (only works for the left controller).|
|*Thumbstick Press*|Uses the thumbstick button's boolean value.|
|*Thumbstick Y*|Uses the thumbstick's linear value from down to up.|
|*Thumbstick Up*|Uses the thumbstick's linear value from center to up.|
|*Thumbstick Down*|Uses the thumbstick's linear value from center to down.|
|*Thumbstick X*|Uses the thumbstick's linear value from left to right.|
|*Thumbstick Left*|Uses the thumbstick's linear value from center to left.|
|*Thumbstick Right*|Uses the thumbstick's linear value from center to right.|

**Comment by zachkinstner** [comment]
The materials used by the controller/hand models (found within "OVR Avatar", Oculus Touch's graphical package) do not work correctly with the Hover UI Kit materials. **The models always render on top of  transparent Hover UI items.** Unfortunately, these components do not provide a way to choose your own materials via the Unity inspector.

So, I recommend making some adjustments for better compatibility. For my [force-directed graph](https://medium.com/@zachkinstner/devup-force-directed-graph-vr-hand-held-user-interface-audio-feedback-downloadable-demo-93bb2dad0bab#.xny26ah3z) project, I made the following changes...

---

#### Step 1
In `AvatarSurfaceShaderPBS.shader`, change the tags to use the non-transparent render queue. This affects the controller material (which has textures for button labels, etc.), but not the hand material.
```cs
Tags {
    "Queue" = "Geometry" //changed
    "RenderType" = "Geometry" //changed
}
```

#### Step 2
In `OvrAvatarRenderComponent.CreateAvatarMaterial()`, find a custom material for the hands:
```cs
Shader s = Shader.Find(shaderPath);
Material mat = new Material(s);
		
if ( !physicallyBasedShader ) { //added this condition, set any material below
    mat = new Material(FindObjectOfType<MyCustomOculusMaterial>().HandMaterial);
}

mat.name = name;
```

#### Step 3
Do something to make your material-finding (from Step 2) work correctly. This probably means creating a script (or using an existing one) that has a material property. 

_Based on the example in Step 2:_ The script would be called `MyCustomOculusMaterial`, and it would have a `HandMaterial` property. You would need to add the component once to your scene, and set the component's "Hand Material" via the Unity inspector. The "Step 2" example finds this component, copies its `HandMaterial`, and applies it to the `OvrAvatar` hand models.

**Comment by zachkinstner** [comment]
As an alternative to Step 2 and Step 3, it looks like you could also write a script that replaces the hand materials after the app starts running. The _hand_left/hand_left_renderPart_0_ and _hand_right/hand_right_renderPart_0_ objects (child objects of _LocalAvatar_) both have a `SkinnedMeshRenderer` component, which is where you can set a new material.

**Comment by zachkinstner** [comment]
Added documentation and animations -- see **[Input Modules: OculusTouch](../wiki/Input-Modules%EA%9E%89-OculusTouch)**.

![OculusTouch Cursors](../wiki/Images/InputModule-OculusTouch-Cursor.gif)

**Comment by michidk** [comment]
Hi Zach,

Is there still no other fix for the issue with the Oculus hands getting rendered on top of the HoverUI than making them solid gray?

**Comment by zachkinstner** [comment]
Hi @michidk, what result are you trying to achieve? 

Opaque materials of any color/style should work with the Oculus Avatar hands -- you're not limited to just gray. Transparent materials could work, but I haven't tested this out in quite a while -- there may be depth issues when the transparent hands get near to (or intersect) the transparent Hover UI items.

Another approach would be to use an opaque material on your Hover UI items, which should avoid the depth conflicts with the default Oculus Avatar materials.

**Comment by osgiliath-stone** [comment]
Hi Zack, this is a little unrelated but I'm having trouble finding help anywhere else. I am using Unity 2018.1.9f1 and version 1.27.0 (OVR Avatar and OVR Utilities) and I cannot figure out how to make the avatar hands have that transparent blue material instead of the default gray material. What would you recommend as I favor the transparent blue look?

**Comment by zachkinstner** [comment]
Hi @jag2013, did you previously change the OVR assets to use the gray material (using the instructions provided earlier in this thread)? If so, you'll likely just need to undo those steps to return to the default transparent hand material. Another option would be to reimport the OVR assets.

As noted above, using the transparent hand material can conflict with Hover UI Kit's transparent materials.

**Comment by osgiliath-stone** [comment]
Hi @zachkinstner, thank you for your response. I didn't change anything like that. I did get a response over at the Oculust Rift/Unity subforum and I was told by one forum contributor that the gray appearance is now the default material applied to the Avatar in the latest version of OVR Avatar.
