### ISSUE TITLE
(ERROR)DemoAdjustInputSceneCamera.cs  

### ISSUE THREAD

**Issue by shenfangch** [aestheticinteractive/Hover-VR-Interface-Kit#55]
Assets/HoverDemos/Common/DemoAdjustInputSceneCamera.cs(31,33): error CS0246: The type or namespace name `BloomOptimized' could not be found. Are you missing a using directive or an assembly reference?

I unzip the file and it turns out this issue. Can you give me some advice?

![capture](https://cloud.githubusercontent.com/assets/10098524/21397618/88af3b10-c772-11e6-8a25-81afb4bb7ac0.PNG)

**Comment by shenfangch** [comment]
`
			if ( UseBloom && cam.GetComponent<BloomOptimized>() == null ) {
				BloomOptimized bloom = cam.gameObject.AddComponent<BloomOptimized>();
				bloom.threshold = 0.35f;
				bloom.intensity = 0.6f;
				bloom.blurSize = 1;
				bloom.blurIterations = 2;
				bloom.blurType = BloomOptimized.BlurType.Standard;
				bloom.fastBloomShader = Shader.Find("Hidden/FastBloom");`

**Comment by zachkinstner** [comment]
Hi @shenfangch, the `BloomOptimized` script comes from Unity's standard assets. You can import these from Unity's top menu: **Assets > Import Package > Effects**

Bloom creates a glowing effect when applied to a camera. Some of the demos use this effect, and as you've discovered here, at least one of the demo scripts depends on it.

https://docs.unity3d.com/Manual/script-BloomOptimized.html

**Comment by shenfangch** [comment]
Thank you so much, Zack

**Comment by zachkinstner** [comment]
I have added a [**Dependencies** section](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Releases-and-Packages#dependencies) to the "releases" wiki page.

> The **Core** module is a dependency for all other modules.

> The **Demos** module (which is typically provided as a `.zip` file in each release) covers a variety of scenarios, and thus depends on most/all **Interface** and **Renderer** modules. It may also depend on one or more **Input** modules, based on which device is desired (or required) for a particular demo scene.

> The **Demos** module also has some external dependencies. Currently, demo scenes depend on:
> - Unity's standard "Effects" assets (in particular, the [BloomOptimized](https://docs.unity3d.com/Manual/script-BloomOptimized.html) component). Import these via Unity's top menu: **Assets > Import Package > Effects**
