### ISSUE TITLE
Improve the way navigation data is provided

### ISSUE THREAD

**Issue by zachkinstner** [aestheticinteractive/Hover-VR-Interface-Kit#6]
@ddutchie wrote:

> If you decide to make this an asset you should definitely make it easier to set up an initial scene. (For Some)
> 
> I'm thinking as an architect here, so imagine for archviz something along these lines. eg: 
> - Hovercraft VR > Scenes, Lighting , Materials, Customization, About, Exit
> - Scenes > Load1, Load2, Load3 etc. - Loads Level/Scene
> - Lighting > Lighting1, Lighting 2, Lighting3. - Lights and Sun behaviour
> - Materials > Set1, Set2, Set3 - Different Materiality settings for a scene
> - Customization > Hovercraft customization
> - About > About Screen - Screen/Large panel with text
> - Exit> Exit to real life.
> 
> In this way you could allow for the dev to drag assets/ groups of assets etc into slots in the scripts and it would just require some scene organisation.
> 
> Regards
> Gerard

**Comment by zachkinstner** [comment]
Hi @ddutchie, thanks for the feedback. Is this what you have in mind?
![Unity Nav Items](http://aestheticinteractive.com/clients/hovercast/UnityNavItems.png)

I have been considering an approach like this for a while now. I'm still relatively new to Unity, and tend to think code-first -- does the above approach seem more familiar for most Unity developers?

Each item within the "Navigation" tree would need an attached [`NavItem`](https://github.com/aestheticinteractive/Hovercast-VR-Menu/blob/master/Unity/Assets/Hovercast/Core/Navigation/NavItem.cs)-based component. There would be different components, with specific settings settings, for the various item types (checkboxes, sliders, etc.).

This approach would essentially replace the way its done in [`DemoNavItems`](https://github.com/aestheticinteractive/Hovercast-VR-Menu/blob/master/Unity/Assets/Hovercast/Demo/DemoNavItems.cs). You could also still do it via code -- building the tree via `new GameObject()` and `AddComponent()`.

**Comment by ddutchie** [comment]
@zachkinstner 

Something like this, I am relatively new to coding. I have done some leap experiments in the past, but I am a 3d modeler and architect firstly. 

![image](https://cloud.githubusercontent.com/assets/10877426/6091512/26fb2b7e-aeb8-11e4-8f4a-9c0ee95ffa27.png)

Lights + Sky1
Lights2 + Sky2
Lights3  + Sky3

Becomes Morning, Midday, Night

![image](https://cloud.githubusercontent.com/assets/10877426/6091529/b91e4734-aeb8-11e4-9a42-c78a3f1bebf6.png)

Obviously the combinations are infinite, but this allows for combinations of menus.
So you could do modules. perhaps even module packs. Where users just need to drag their assets into the slots. 

If you could link the position of the sun to a slider would be even better,  or to a watch on the topside of the arm. epic.

Like I've mentioned I am an amateur coder, but I am a good problem solver, I tend to figure a route about a problem. 

But My code is messy.

**Comment by ddutchie** [comment]
I can send you a demo of what I have achieved with your asset.

**Comment by zachkinstner** [comment]
@ddutchie thanks for this! I should have some time to review it more closely on Monday or Tuesday. In the meantime, please feel free to send me a link to your demo.

**Comment by ddutchie** [comment]
I'm having some issues with the HovercastLeapInputProvider when this is attached in the scene I am unable to look around before the VR safety message disappears, why is this? 

Specifically looking left and right.

**Comment by zachkinstner** [comment]
> looking left and right [...] before the VR safety message disappears

@ddutchie this occurs in the demo's code: https://github.com/aestheticinteractive/Hovercast-VR-Menu/blob/master/Unity/Assets/Hovercast/Demo/DemoEnvironment.cs#L184. Perhaps you copied it over to your demo?  The cubes demo doesn't have an obvious "forward" direction, however, the camera movements still occur relative to that direction. To help initialize correctly, the demo constantly re-centers the view until the warning disappears. Maybe not the best solution, but good enough for the demo's needs. Removing [this line of code](https://github.com/aestheticinteractive/Hovercast-VR-Menu/blob/master/Unity/Assets/Hovercast/Demo/DemoEnvironment.cs#L198) should avoid this behavior.

**Comment by zachkinstner** [comment]
I have made significant progress on this in the **[unitynav](https://github.com/aestheticinteractive/Hovercast-VR-Menu/tree/unitynav)** branch. The navigation is created as a GameObject hierarchy (with `HovercastNavItem` components attached). I revised the customization features to work in a similar way. This reduces the amount of code that needs to be written.  I hope to complete these changes tomorrow, and also add the documentation.

To see how the new approach currently works, you can view the [`HovercastDemo-Test.unity`](https://github.com/aestheticinteractive/Hovercast-VR-Menu/blob/unitynav/Unity/Assets/Hovercast/Demo/Scenes/HovercastDemo-Test.unity) scene. The other scenes don't support the latest changes yet.

**Comment by zachkinstner** [comment]
All scenes in the **unitynav** branch now support the latest approach. Tomorrow I will be merging this into the **master** branch and writing some documentation.

**Comment by ddutchie** [comment]
Awesome. Downloading now. Did you see this,
http://www.fastcodesign.com/3042117/control-this-vr-menu-by-altering-your-hand-gestures

Regards

On 11 February 2015 at 06:26, Zach Kinstner notifications@github.com
wrote:

> All scenes in the _unitynav_ branch now support the latest approach.
> Tomorrow I will be merging this into the _master_ branch and writing some
> documentation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/6#issuecomment-73832572
> .

## 

Gerard Slee

**Comment by ddutchie** [comment]
Clever implementation within the hierarchy. Loving this.

On 11 February 2015 at 09:25, Gerard Slee ddutchie@gmail.com wrote:

> Awesome. Downloading now. Did you see this,
> http://www.fastcodesign.com/3042117/control-this-vr-menu-by-altering-your-hand-gestures
> 
> Regards
> 
> On 11 February 2015 at 06:26, Zach Kinstner notifications@github.com
> wrote:
> 
> > All scenes in the _unitynav_ branch now support the latest approach.
> > Tomorrow I will be merging this into the _master_ branch and writing
> > some documentation.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/6#issuecomment-73832572
> > .
> 
> ## 
> 
> Gerard Slee

## 

Gerard Slee

**Comment by ddutchie** [comment]
still working on a demo.
trying to get the filesize down a bit.

On 11 February 2015 at 15:26, Gerard Slee ddutchie@gmail.com wrote:

> Clever implementation within the hierarchy. Loving this.
> 
> On 11 February 2015 at 09:25, Gerard Slee ddutchie@gmail.com wrote:
> 
> > Awesome. Downloading now. Did you see this,
> > http://www.fastcodesign.com/3042117/control-this-vr-menu-by-altering-your-hand-gestures
> > 
> > Regards
> > 
> > On 11 February 2015 at 06:26, Zach Kinstner notifications@github.com
> > wrote:
> > 
> > > All scenes in the _unitynav_ branch now support the latest approach.
> > > Tomorrow I will be merging this into the _master_ branch and writing
> > > some documentation.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/6#issuecomment-73832572
> > > .
> > 
> > ## 
> > 
> > Gerard Slee
> 
> ## 
> 
> Gerard Slee

## 

Gerard Slee

**Comment by zachkinstner** [comment]
> Clever implementation within the hierarchy. Loving this.

Great! Glad to hear it. I just merged **unitynav** into the **master** branch, and some documentation is coming soon.

Thanks for posting the link to the article. I did see that last night -- exciting! This morning there was a new article on Mashable: http://mashable.com/2015/02/11/hovercast-virtual-reality/

**Comment by zachkinstner** [comment]
New documentation is in progress:
https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Getting-Started

**Comment by ddutchie** [comment]
Awesome. Good for you! 

How would i go about using my sight to select and move the cursor. 

I already have a script attached to an empty game object which  casts a ray  from the left camera. I was using it to get coordinates for my depth of field script. It works, but unfortunately it intersects with mesh colliders only and my models are rarely optimized. I have to be sneaky with what gets collision. DOF off for now. 

This script is ideal. 

Instead of the cursor on my right index  (which has been causing issues with my coworkers(architects))  It should appear when i stare at your VR menu. 
Using the coordinates it gets from the empty game object. 

I'll have to look tomorrow. GMT +2 over here. 
I Still need to inspect and merge your latest changes. 

Sounds so easy. I'll figure it out. 

Anyways. Good luck. I imagine its gonna get hectic on your side shortly.

**Comment by zachkinstner** [comment]
New/updated docs:
- https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Types-of-Menu-Items
- https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Menu-Item-Listeners

**Comment by zachkinstner** [comment]
> How would i go about using my sight to select and move the cursor?

@ddutchie interesting feature idea! 

I'm not sure if/when I'd get to it, but I have created a new issue for this: https://github.com/aestheticinteractive/Hovercast-VR-Menu/issues/7

**Comment by zachkinstner** [comment]
The "Getting Started" documentation is updated:
https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Getting-Started

I'm thinking about also adding a "Quick Start" document that does the bare minimum to get a menu in your hand.

**Comment by zachkinstner** [comment]
Here's the "Quick Start" guide, with corresponding GIF animation:

https://github.com/aestheticinteractive/Hovercast-VR-Menu/wiki/Quick-Start
