### ISSUE TITLE
Look Cursor Goes to Hovercast local space. How to get back to World Space?

### ISSUE THREAD

**Issue by imyjimmy** [aestheticinteractive/Hover-VR-Interface-Kit#61]
Hi Zach,
I'm using Hover's Look cursor and the Hovercast Interface Module which is attached to my left hand. When I activate Hovercast and look at its general direction, the Look cursor jumps into Hovercast's local space. How do I get the look cursor back in world space when I de-activate Hovercast?

Thanks,

Jimmy

**Comment by zachkinstner** [comment]
It looks like you found a bug. When searching for the best item, the "Look" cursor's raycast currently does not consider the active/inactive state of an item.

For an immediate workaround, pelase try this: at line 77 of [`HoverItemsRaycastManager`](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/8a2a3b3ef581efa135c1e22b621f801d6a4aa694/Unity/Assets/Hover/Core/Scripts/Items/Managers/HoverItemsRaycastManager.cs#L77), you can add a new condition to the `if` statement:

```cs
if ( !item.isActiveAndEnabled || item.IsHighlightPreventedViaAnyDisplay() ) {
	continue;
}
```

I ran a quick test with this change, and it seems to resolve the issue. In the test, I had a Hovercast menu with a separate item placed behind it. Upon deactivating the Hovercast object, the "Look" cursor now jumps onto the other item's plane/space. And upon re-activating Hovercast, the "Look" cursor returns to the Hovercast plane/space as expected.

**Comment by imyjimmy** [comment]
Thanks! Just saw this. Closing
