### ISSUE TITLE
Unity 5.3.4 compatibility

### ISSUE THREAD

**Issue by mihaimpop** [aestheticinteractive/Hover-VR-Interface-Kit#63]
Hi **@zachkinstner** 
I'm developing an app which requires I use an older version of **Unity**, namely **5.3.4f1**, and an older version of the **Orion** library. All of this in order to stream through **Riftcat's Vridge**.

The issue is that **Unity** crashes every time with the **2.0.0A** and **2.0.0B** releases.

Should I use **1.4.0** release? 
Is there a way to import the new **shiny** package in this version of **Unity**?
Is there a way to 'port' the package from a higher version of **Unity**?

**Comment by mihaimpop** [comment]
Oh, it makes sense. You switched to Unity 5.5 in the commit on Feb 7, 2017. Different serialization in Unity 5.5. No backwards compatibility. 
I'll see myself out.

**Comment by zachkinstner** [comment]
Hi @mihaimpop, I'm not sure if the Hover UI Kit v2.x.x series would work with the older Unity versions. I'll throw in some ideas, though -- maybe it's possible.

Are you trying to run a Hover UI example scene? If the Unity compatibility issue is primarily with the scene serialization format, I wonder if it would work to build up a brand new scene in Unity 5.3. Prefabs are also serialized, of course, but perhaps they are "more compatible" than a scene.

All the Unity assets in the Hover UI repository are serialized as text, which means that you could potentially do some search-and-replace work on those files. Perhaps there are a few changes to the scene and/or prefab files that would make them load/run with Unity 5.3?

[This Unity Answers thread](http://answers.unity3d.com/questions/1279010/unity-55-downward-compatibility.html) discusses compatibility, and includes a link to a [compatibility-fixing](https://gist.github.com/Seneral/d88d2079ff17f77f2bd1775aadb8547b) script that might be useful for you.
