### ISSUE TITLE
The type or namespace name `ImageEffects' does not exist in the namespace

### ISSUE THREAD

**Issue by lilyzhng** [aestheticinteractive/Hover-VR-Interface-Kit#64]
I have already imported the standard assets package. And the editor version I am using is 5.5.1f1

**Comment by zachkinstner** [comment]
Hi @alchemz! As a starting point, please confirm that the following folder/file exists in your project:

`Assets/Standard Assets/Effects/ImageEffects/BloomOptimized.cs`

You mentioned that you already imported Unity's Standard Assets package, but I just want to make sure that it's completely imported. It's possible to accidentally delete or exclude some portions of that package, so I'm trying to rule out the basics before looking deeper.

If that file _does_ exist, please send the full stack-trace of the error message(s) that you're seeing in Unity.

**Comment by rahb3rt** [comment]
I had the same problem originally.. you have to get the legacy assets which are in the Unity store available for download. Then the standard assets will import as well the ones that you are looking for. Current HoverUI uses deprecated assets or reorganized ones.

**Comment by zachkinstner** [comment]
Thanks for the note @rahb3rt -- I was not aware that Unity changed the asset package. I just imported the assets in a new project, and the `.../ImageEffects` directory now only contains this `Readme.txt` file:

> The old image effects have been deprecated and moved to the Asset Store: https://www.assetstore.unity3d.com/#!/content/83913
> 
> We recommend that you now use the new post-processing stack. You'll find it at https://www.unity3d.com/postprocessing

**Comment by rahb3rt** [comment]
@zachkinstner will HoverUI move to the new post processing stack any time soon? Or will you guys stick to the deprecated library?

**Comment by zachkinstner** [comment]
I'm currently focused on development of my VR music app ([EXA: The Infinite Instrument](http://store.steampowered.com/app/606920)), so its unlikely that there will be Hover UI Kit updates in the near-term.

However, the only part of Hover UI Kit that uses the `ImageEffects` package are its **demo scenes/scripts**, which you get when you pull down the entire repository. I think there's only [one script](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/8412fa125303271daaa84120564df111b5aa1def/Unity/Assets/HoverDemos/Common/DemoAdjustInputSceneCamera.cs) and one type of in-scene reference (`Bloom (Opimized)` on some of the cameras) that reference the old `ImageEffects` package.

If you install Hover UI Kit from the [release packages](https://github.com/aestheticinteractive/Hover-UI-Kit/releases), you will not have these dependencies, and should not have any issues.

**Comment by autuus** [comment]
For lazy readers, solution: import https://www.assetstore.unity3d.com/#!/content/83913

**Comment by autuus** [comment]
https://www.assetstore.unity3d.com/#!/content/83913

**Comment by zachkinstner** [comment]
I have just posted the new [**Hover UI Kit v2.0.1B**](https://github.com/aestheticinteractive/Hover-UI-Kit/releases/tag/v2.0.1B) release, which fixes this issue by removing the "Hover Demos" dependency on the "Legacy Image Effects" pacakge.

**Comment by ghost** [comment]
I don't why anyone would have to remove Bloom filter or remove the "Legacy Image Effects", because it still works, all you need to add to your scripts that use ImageEffectBase is:

using UnityStandardAssets.ImageEffects; //add this and your legacy Image Effects will work fine

For example, in any legacy image effect script like Bloom or EdgeDetectEffect, add that line after "using UnityEngine;"
You can use the new Post-Processing Stack from Unity, but you can also use the legacy in the same project.
