### ISSUE TITLE
Question about HoverInputSceneLoader

### ISSUE THREAD

**Issue by rahb3rt** [aestheticinteractive/Hover-VR-Interface-Kit#70]
I had a question about the HoverInputSceneLoader -I believe thats in one of the demos.. 

Does it contain a function that will call Vive or Oculus or Leapmotion depending which one is plugged in?

If so how do I go about activating it?

Thank you!

**Comment by zachkinstner** [comment]
Hi @rahb3rt, I think you're referring to the [`HoverSceneLoader`](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/master/Unity/Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs) component. And to answer your question: no, it doesn't do any device-detection. The Hover Demo scenes are setup for you to manually enable the input device that you want to use.

The device-detection itself is fairly simple:

```cs
var leapControl = new Controller();
leapControl.StartConnection();

bool isLeap = (leapControl.IsServiceConnected && leapControl.IsConnected);
bool isVive = (VRSettings.loadedDeviceName == "OpenVR");
```

The check for Leap Motion sometimes needs to wait until `Start()` or the first `Update()` -- it doesn't always report the connection on `Awake()`.

Beyond this detection, the logic becomes very dependent on your app's needs. My [Force-Directed Graph](https://gallery.leapmotion.com/force-directed-graph/) VR data-viz project chooses between three different "input" scenes. My [EXA: The Infinite Instrument](http://store.steampowered.com/app/606920) VR music project is more complicated, choosing between Vive or Oculus "input" scenes, then optionally loading Leap Motion support and (if it is present) disabling some-but-not-all of the Vive/Oculus support.
