### ISSUE TITLE
fail to update value from HoverItemDataSlider 

### ISSUE THREAD

**Issue by kunkunkunkun** [aestheticinteractive/Hover-VR-Interface-Kit#71]
Hi, Zach, thank you so much for helping me out at the previous problem ! While when i try to align value from HoverItemDataSlider  to my script it failed to update the value . The value changed only when if i restart simulation or select the object with HoverItemDataSlider script attached 
![1](https://user-images.githubusercontent.com/29138261/27119332-0553fb1e-5112-11e7-96e7-e1f04241a238.PNG)
this is my code and i have align the result_value with a variable called "values" inside HoverItemDataSlider 
![2](https://user-images.githubusercontent.com/29138261/27119331-05535cea-5112-11e7-9ced-80cc7a28e636.PNG)
this is what i got with other object selected 
![3](https://user-images.githubusercontent.com/29138261/27119333-056a029c-5112-11e7-90c2-5a45bbc8325b.PNG)
this is waht i got with slideritem(arcslider(1)) selected

**Comment by zachkinstner** [comment]
Hi @kunkunkunkun, the [`HoverItemDataSlider`](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/master/Unity/Assets/Hover/Core/Scripts/Items/Types/HoverItemDataSlider.cs) class does not have a `values` property. Is the `h.values` property something that you added?

To obtain the slider value from your slider named `h`, use...

- `h.Value`: The raw slider value. Returns a result from 0 to 1.
- `h.RangeValue`: The slider value using the slider's min/max range. In most cases, this is the value you want to obtain. Returns a result from `h.MinValue` to `h.MaxValue`.

There are "snapped" versions of both properties (`h.SnappedValue` and `h.SnappedRangeValue`). These are useful if your slider component uses the "Snaps" setting -- typically you'd use this to snap the slider handle to the nearest tick mark.

**Comment by kunkunkunkun** [comment]
Alright, thank you for pointing that out ! The RangeValue is actually an integer which can be accessed directly.  Thank you soooo much ! :D
