### ISSUE TITLE
Raycast on Finger

### ISSUE THREAD

**Issue by rahb3rt** [aestheticinteractive/Hover-VR-Interface-Kit#72]
Hey,
Was wondering, how do you manage to cast a raycast using the fingers in leapmotion? And would there be anyway to access the data or perhaps create separate scripts to generate that data?

Best and thank you!

**Comment by zachkinstner** [comment]
Hover UI uses [this code](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/4a5099ceafb3045da94c9cab2c7572732ea89f92/Unity/Assets/Hover/InputModules/LeapMotion/Scripts/HoverInputLeapMotion.cs#L119) to obtain the distal bone's "basis" rotation (of `Quaternion` type). The basic parts are:

```
Bone distalBone = myLeapFinger.Bone(Bone.BoneType.TYPE_DISTAL);
Quaternion boneRotation = distalBone.Basis.CalculateRotation();
```

You can multiply this rotation with a local "forward" direction (like `Vector3<0, 0, 1>`) to get the ray's world-space direction. A good origin for the ray is the Leap finger's `TipPosition`.

**Comment by zachkinstner** [comment]
Regarding your second question:

You won't need to do anything too involved to obtain this information from Hover UI. Each of the Leap Motion fingertip-based cursors has their transform set to the correct position and rotation each frame, as described in my previous comment. 

By reading the position/rotation information from these transforms, or accessing it via [`ICursorData`](https://github.com/aestheticinteractive/Hover-UI-Kit/blob/f4214c55084cc61fd07f59799edc5cd1b12670c7/Unity/Assets/Hover/Core/Scripts/Cursors/ICursorData.cs) (see the `WorldPosition` and `WorldRotation` properties), you should be able to raycast outward from any particular cursor.
