### ISSUE TITLE
Trying example scenes with Vive

### ISSUE THREAD

**Issue by andybak** [aestheticinteractive/Hover-VR-Interface-Kit#73]
What I've tried:

1. Download the zip of Hover-UI-Kit
2. Open it in Unity
3. Import Unity Standard Assets and SteamVR from the asset store
4. Edit the code to fix the error about missing bloom effects (no longer included in standard assets
5. Add HOVER_INPUT_VIVE to define symbols
6. Open an example scene
7. Add InputSceneLoader and edit string params ( Hover/InputModules/Vive/Scenes/ and HoverInputModule-Vive )
8. Tick auto-load in editor
9. Press play...

Now I'm not sure what's supposed to happen here but for every scene I try I get no errors in the console.I can see hover UI elements but they aren't attached to my controllers.

And none of the controller inputs do anything. 

I had similar results starting my own scene and using the prefabs.

One suggestion - include a demo scene already set up for each input module just so new users can confirm everything works and get a feel for what the library does.

**Comment by zachkinstner** [comment]
Hi @andybak,

Let's see if we can figure out what's going on. Let's start with...

>6. Open an example scene

Which scene? For now, I'll assume something like like the "CastCubes.unity" example scene.

> 7. Add InputSceneLoader and edit string params

The example scenes already include this prefab... are you adding another one?

In the CastCubes scene, for example, the "InputSceneLoader (enable one)" prefab is the first object in the hierarchy. It has several child objects -- you'll want to **enable** the "Vive" child, and **disable** all other children (including the "None" child).

> I can see hover UI elements but they aren't attached to my controllers.

If multiple input modules are open, Hover UI will pick just one of them to use for input. So, as a first step, please make sure that the "InputSceneLoader" has only one enabled child.

As a next step, please confirm that the `HoverInputVive` component is attached to the "[CameraRig]" object (and is enabled) in your "HoverInputModule-Vive" scene. This component is responsible for sending the Vive input data to the Hover UI cursors.

**Comment by coa12sd** [comment]
Hi I am also having a problem with getting this to work with the vive. 

It will not let me attach the HoverInputVive Script to my camera rig as it says there is compile errors (of which there are none) or class name is not the same as file name. When using the scene loader I can load in your camera rig and it says the HoverInputVive script on there cannot be loaded. I have followed all instructions for set up and defined the symbol correctly

Could this be a problem introduced by a newer version of unity I am using 5.6.2?

**Comment by coa12sd** [comment]
Ok I fixed my problem not 100% sure how but I do not think unity loaded the ViveCursor script properly as after I looked at that script in the editor it suddenly worked

**Comment by andybak** [comment]
I got CastCubes (sort of) working with a Rift so I'll close this ticket for now.
