### ISSUE TITLE
The type or namespace name `UnityStandardAssets' could not be found. Are you missing an assembly reference?

### ISSUE THREAD

**Issue by dipottor** [aestheticinteractive/Hover-VR-Interface-Kit#74]
Hi, Opening the project of your git repo. But getting above error.can you please help confirm what is I am missing?

**Comment by zachkinstner** [comment]
Hi @dipottor, this is likely due to a Unity change (since my latest work on Hover UI Kit) that removed the standard "Bloom" filter, which is used only by the Hover demo scenes.

Please see issue #64 for a likely fix.

**Comment by zachkinstner** [comment]
The fix is now available in the [**Hover UI Kit v2.0.1B**](https://github.com/aestheticinteractive/Hover-UI-Kit/releases/tag/v2.0.1B) release. See #64 for more details.
