### ISSUE TITLE
Interaction with Unity UI

### ISSUE THREAD

**Issue by YugiyO** [aestheticinteractive/Hover-VR-Interface-Kit#75]
Hi, I just working on VR project with OSVR and Leap Motion, and I just find this Hover UI and use its Raycast function in my project, so I wonder that does Hover UI Raycast compatible with Unity UI Interaction? I try to find a way for a while but have no luck because I am newbie in Raycast. Moreover, I just come up with the idea to use Raycast for player movement controlling, is it possible to do this with Hover UI Raycast as well?

**Comment by zachkinstner** [comment]
Hi @YugiyO! I have not attempted to use Hover UI Kit for interacting with the standard Unity UI elements. It seems like it should be possible with some custom code -- I think the general idea would be to pass information about the Hover UI cursors/raycasts into Unity's [Event System](https://docs.unity3d.com/Manual/EventSystem.html).
