### ISSUE TITLE
Multiple Depricated Dependencies

### ISSUE THREAD

**Issue by autuus** [aestheticinteractive/Hover-VR-Interface-Kit#77]
Assets/Hover/InputModules/OculusTouch/Scripts/OculusTouchCursor.cs(120,36): error CS1061: Type `UnityEngine.Matrix4x4' does not contain a definition for `GetRotation' and no extension method `GetRotation' of type `UnityEngine.Matrix4x4' could be found. Are you missing an assembly reference?

Hmm.. 

Its discussed here https://github.com/aestheticinteractive/Hover-UI-Kit/issues/57 but I don't know how to import that function... since i dont know how to use this keyword in C#

So i just commented it out, there was another error about editor, but i commented that out, so, it didnt work.

Hover-UI-Kit-2.0.0B

**Comment by zachkinstner** [comment]
Hi @autuus!

In issue #57, my [second comment](https://github.com/aestheticinteractive/Hover-UI-Kit/issues/57#issuecomment-269995820) says that the `GetRotation()` extension method is not actually needed by Hover UI Kit, so it can be removed. Please replace the `UpdateDataWithLocalOffsets()` method (code provided in my comment) to fix the issue.

If you _do_ need to use the `GetRotation()` extension method for some reason (the code extracts the rotation component from a 4x4 matrix), you could either import the SteamVR package, or use the code provided in my first comment in #57.

**Comment by zachkinstner** [comment]
Here is the diff for that replacement code: https://github.com/aestheticinteractive/Hover-UI-Kit/commit/c282ca3b74d6d2e4524e70a55a481d43d7f84a50

**Comment by autuus** [comment]
okay, got it, 
when i enter playmode leap is not tracking, I can see the menus though. I enabled leap from the example though, but nada


when i exit play mode ArgumentException: Scene to unload is invalid
UnityEngine.SceneManagement.SceneManager.UnloadSceneInternal (Scene scene) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneManagerBindings.gen.cs:170)
UnityEngine.SceneManagement.SceneManager.UnloadScene (Scene scene) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneManagerBindings.gen.cs:165)
Hover.Core.Utils.HoverSceneLoader.OnDestroy () (at Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs:45)

**Comment by autuus** [comment]
Enabling oculus touch Scene 'Hover/InputModules/OculusTouch/Scenes/HoverInputModule-OculusTouch' couldn't be loaded because it has not been added to the build settings or the AssetBundle has not been loaded.
To add a scene to the build settings use the menu File->Build Settings...
UnityEngine.SceneManagement.SceneManager:LoadScene(String, LoadSceneMode)
Hover.Core.Utils.HoverSceneLoader:LoadSceneForRuntime() (at Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs:108)
Hover.Core.Utils.HoverSceneLoader:LoadScene() (at Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs:78)
Hover.Core.Utils.HoverSceneLoader:Awake() (at Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs:34)

**Comment by zachkinstner** [comment]
Hmm, I'm not sure what might be happening regarding Leap Motion. If the Leap Motion controller is not tracking properly, you'll want to make sure the device is turned on, connected, and that your Leap Motion SDK is imported correctly, etc.

On the Hover UI Kit side, please be sure to review the various [Getting Started](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Getting-Started) pages, and also the [Input Modules](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules) and [Leap Motion](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules%EA%9E%89-LeapMotion) pages. Following the steps and instructions on these pages will avoid many issues while getting Hover UI Kit setup for your app.

> Enabling oculus touch Scene...

This error message is telling you what Unity requires -- the scene must be added to the "Scenes In Build" list in the "Build Settings" menu.

**Comment by autuus** [comment]
Im making an augmented/virtual reality OS https://autuus.itch.io/avros With leap motion + zed stereocamera and oculus, no sensors needed, its completely mobile ^^

**Comment by autuus** [comment]
Okay then, leap works in my other project though.. Lets see if I can crack this code.

**Comment by autuus** [comment]
Okay, adding the scene to build didnt work 
Its a bit unintuitive anyways, since i'm trying to debug it, not really compile or build

screenshot https://imgur.com/a/WjPgrOA

**Comment by zachkinstner** [comment]
The error message tells you which scene must be added. In the case of the error message you provided above, the additional scene is "Hover/InputModules/OculusTouch/Scenes/HoverInputModule-OculusTouch". In your screenshot, there is only one scene present in the list (the "KeyboardPixels" example scene).

**Comment by zachkinstner** [comment]
Also, please note that Hover UI Kit only supports one input module at a time. In you screenshot, it appears you're trying to use both the Oculus and Leap Motion input modules together.

**Comment by autuus** [comment]
> Also, please note that Hover UI Kit only supports one input module at a time. In you screenshot, it appears you're trying to use both the Oculus and Leap Motion input modules together.

Good to know, but only none has a camera, so I just make new camera, or is it none + 1 more?

**Comment by zachkinstner** [comment]
The cameras are present in the Input Module scenes. For example, in the "HoverInputModule-OculusTouch" scene, you'll find both the "OVRCameraRig" prefab and the "LocalAvatar" prefab.

In the "KeyboardPixels" example, these scenes are loaded at runtime by whichever (one) child of "InputSceneLoaders" that you enable. For example, the "OculusTouch" child object has a "Hover Scene Loader" component that performs this action.

This information is described in the wiki pages I linked above. I know it can be a drag to read through the documentation, but it's going to save you from a lot of headaches while getting started with Hover UI Kit.

**Comment by autuus** [comment]
Hmm, looks like my error was that I didnt import leap motion sdk. Lets see if I'm able to import it properly..

**Comment by autuus** [comment]
Hmm, it says missing prefab on all imput module scenes https://imgur.com/a/mQBgLZf

**Comment by zachkinstner** [comment]
I can't tell from your screenshot -- do you have the Leap Motion SDK imported into your Unity project? This scene is trying to find the "LMHeadMountedRig" prefab, which is provided by the Leap Motion SDK.

**Comment by autuus** [comment]
yeah, I had to copypaste it, since its not in asset store. it works but maybe its not detected by this code
I give up.
For now, at least.

**Comment by zachkinstner** [comment]
You can download Leap Motion's Unity SDK (called "Core Assets") here:
https://developer.leapmotion.com/unity/#5436356

If you copy-pasted some SDK assets, be sure to also include the "*.meta" files. If those files are not included, Unity will re-create them, and the script/prefab references will be lost.

**Comment by autuus** [comment]
Okay, once more, I download the 2.0.0B, Import the depricated version of Image Effects, import oculus integration and leap, fix the broken function, and come to the epic conclusion, it doesn't work.

no errors, just no hand and no camera.
missing prefab in HoverInput module.

**Comment by zachkinstner** [comment]
### Test

- New project in Unity 2017.3.1f1
- Download the two `2.0.0B` ZIP files [here](https://github.com/aestheticinteractive/Hover-UI-Kit/releases)
- Import all the Hover UI Kit packages (core, input modules, interface modules)
- Add the "HoverDemos" folder to the project
- Download/import the [Unity Legacy Image Effects](https://assetstore.unity.com/packages/essentials/legacy-image-effects-83913) package (only needed for "HoverDemos" content)
- Download/import the [Leap Motion Core Assets 4.4.0](https://developer.leapmotion.com/unity/#5436356) package
- Leap Motion popup appears in Unity with a "Leap Rig Updater" warning, saying that the rigging prefab has changed in version 4.4.0
- Try running the "Leap Rig Updater" in the `HoverInputModule-LeapMotion` scene -- it does nothing

### Conclusion

Leap Motion SDK v4.4.0 has breaking changes for Hover UI Kit's Leap Motion input module. That's frustrating. Looks like this version was released about three weeks ago.

### Workaround

You can use Leap Motion Core Assets 4.3.4 ([download here](https://github.com/leapmotion/UnityModules/releases/tag/Release-CoreAsset-4.3.4)) for now, until I can implement a new version of the input module.

**Comment by autuus** [comment]
Okay, got it working finally. I still do get an error, ArgumentException: Scene to unload is invalid
UnityEngine.SceneManagement.SceneManager.UnloadSceneInternal (Scene scene) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneManagerBindings.gen.cs:170)
UnityEngine.SceneManagement.SceneManager.UnloadScene (Scene scene) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/SceneManagerBindings.gen.cs:165)
Hover.Core.Utils.HoverSceneLoader.OnDestroy () (at Assets/Hover/Core/Scripts/Utils/HoverSceneLoader.cs:45)

When exiting debug mode. any recommendations on how to fix this?

**Comment by autuus** [comment]
Here's a version for the ones that want it to **just work**, without invested effort.
[Unity Hover UI test project](http://51.38.185.65/HoverUITest.rar)
(estimated lifetime for link is half a year)

**Comment by zachkinstner** [comment]
Thanks for uncovering the issue caused by the new Leap Motion assets!

I have just posted the new [**Hover UI Kit v2.0.1B**](https://github.com/aestheticinteractive/Hover-UI-Kit/releases/tag/v2.0.1B) release. This release fixes the Leap Motion issue and other compatibility-related issues that have arisen over the past year or so. Please give it a try, and let me know whether it resolves the issues you were having.

I have also updated the [Input Module > Leap Motion](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Input-Modules%EA%9E%89-LeapMotion#sdk) page with notes about compatibility.
