### ISSUE TITLE
Registering hovercast events

### ISSUE THREAD

**Issue by autuus** [aestheticinteractive/Hover-VR-Interface-Kit#78]
I'm just going to ask this since I think the question is relevant for everyone. How do I properly register HoverCast events? I usually just hack around until I find a good enough solution, its usually bad for elegance.
I need to register events such as checkbox checked/unchecked, from the context of any script.

**Comment by zachkinstner** [comment]
Hi @autuus! From the [Items: Data and Events](https://github.com/aestheticinteractive/Hover-UI-Kit/wiki/Items#item-data-and-events) wiki:

> Each item type has its own data component, such as HoverItemDataCheckbox and HoverItemDataSlider. These components are responsible for maintaining their item's values, and for triggering the item's events.

> [...] These components all provide type-specific events, which you can use to trigger actions in your scene. These are in the Unity inspector's "Events" foldout. 

You can also listen to these events via script, for example:

```c#
HoverItemDataCheckbox myCheckboxItem = /* get the item */;
myCheckboxItem.OnSelectedEvent.AddListener(MyListenerMethod);
```

**Comment by zachkinstner** [comment]
Related issues: #65, #68
